/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Ethernet_simple_32                                    *
* Dimensions:  32 * 32                                               *
* NumColors:   9                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmEthernet_simple_32;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsEthernet_simple_32[] = {
  0xFFFFFF, 0x000000, 0x575757, 0xA7A7A7,
  0xB7B7B7, 0x0E0E0E, 0x1E1E1E, 0xD3D3D3,
  0x8F8F8F
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalEthernet_simple_32 = {
  9,  // Number of entries
  1,  // Has transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acEthernet_simple_32[] = {
  /* RLE: 075 Pixels @ 000,000 */ 75, 0x00, 
  /* RLE: 001 Pixels @ 011,002 */ 1, 0x04, 
  /* RLE: 008 Pixels @ 012,002 */ 8, 0x03, 
  /* RLE: 001 Pixels @ 020,002 */ 1, 0x04, 
  /* RLE: 021 Pixels @ 021,002 */ 21, 0x00, 
  /* RLE: 001 Pixels @ 010,003 */ 1, 0x04, 
  /* RLE: 010 Pixels @ 011,003 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 021,003 */ 1, 0x04, 
  /* RLE: 020 Pixels @ 022,003 */ 20, 0x00, 
  /* RLE: 001 Pixels @ 010,004 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 011,004 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 021,004 */ 1, 0x03, 
  /* RLE: 020 Pixels @ 022,004 */ 20, 0x00, 
  /* RLE: 001 Pixels @ 010,005 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 011,005 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 021,005 */ 1, 0x03, 
  /* RLE: 020 Pixels @ 022,005 */ 20, 0x00, 
  /* RLE: 001 Pixels @ 010,006 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 011,006 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 021,006 */ 1, 0x03, 
  /* RLE: 020 Pixels @ 022,006 */ 20, 0x00, 
  /* RLE: 001 Pixels @ 010,007 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 011,007 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 021,007 */ 1, 0x03, 
  /* RLE: 020 Pixels @ 022,007 */ 20, 0x00, 
  /* RLE: 001 Pixels @ 010,008 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 011,008 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 021,008 */ 1, 0x03, 
  /* RLE: 020 Pixels @ 022,008 */ 20, 0x00, 
  /* RLE: 001 Pixels @ 010,009 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 011,009 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 021,009 */ 1, 0x03, 
  /* RLE: 020 Pixels @ 022,009 */ 20, 0x00, 
  /* RLE: 001 Pixels @ 010,010 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 011,010 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 021,010 */ 1, 0x03, 
  /* RLE: 020 Pixels @ 022,010 */ 20, 0x00, 
  /* ABS: 002 Pixels @ 010,011 */ 0, 2, 0x75, 
  /* RLE: 008 Pixels @ 012,011 */ 8, 0x01, 
  /* ABS: 002 Pixels @ 020,011 */ 0, 2, 0x57, 
  /* RLE: 025 Pixels @ 022,011 */ 25, 0x00, 
  /* ABS: 002 Pixels @ 015,012 */ 0, 2, 0x22, 
  /* RLE: 030 Pixels @ 017,012 */ 30, 0x00, 
  /* ABS: 002 Pixels @ 015,013 */ 0, 2, 0x22, 
  /* RLE: 030 Pixels @ 017,013 */ 30, 0x00, 
  /* ABS: 002 Pixels @ 015,014 */ 0, 2, 0x22, 
  /* RLE: 015 Pixels @ 017,014 */ 15, 0x00, 
  /* RLE: 001 Pixels @ 000,015 */ 1, 0x08, 
  /* RLE: 014 Pixels @ 001,015 */ 14, 0x02, 
  /* ABS: 002 Pixels @ 015,015 */ 0, 2, 0x66, 
  /* RLE: 014 Pixels @ 017,015 */ 14, 0x02, 
  /* ABS: 002 Pixels @ 031,015 */ 0, 2, 0x88, 
  /* RLE: 006 Pixels @ 001,016 */ 6, 0x02, 
  /* ABS: 002 Pixels @ 007,016 */ 0, 2, 0x66, 
  /* RLE: 014 Pixels @ 009,016 */ 14, 0x02, 
  /* ABS: 002 Pixels @ 023,016 */ 0, 2, 0x66, 
  /* RLE: 006 Pixels @ 025,016 */ 6, 0x02, 
  /* RLE: 001 Pixels @ 031,016 */ 1, 0x08, 
  /* RLE: 007 Pixels @ 000,017 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 007,017 */ 0, 2, 0x22, 
  /* RLE: 014 Pixels @ 009,017 */ 14, 0x00, 
  /* ABS: 002 Pixels @ 023,017 */ 0, 2, 0x22, 
  /* RLE: 014 Pixels @ 025,017 */ 14, 0x00, 
  /* ABS: 002 Pixels @ 007,018 */ 0, 2, 0x22, 
  /* RLE: 014 Pixels @ 009,018 */ 14, 0x00, 
  /* ABS: 002 Pixels @ 023,018 */ 0, 2, 0x22, 
  /* RLE: 014 Pixels @ 025,018 */ 14, 0x00, 
  /* ABS: 002 Pixels @ 007,019 */ 0, 2, 0x22, 
  /* RLE: 014 Pixels @ 009,019 */ 14, 0x00, 
  /* ABS: 002 Pixels @ 023,019 */ 0, 2, 0x22, 
  /* RLE: 009 Pixels @ 025,019 */ 9, 0x00, 
  /* ABS: 002 Pixels @ 002,020 */ 0, 2, 0x75, 
  /* RLE: 008 Pixels @ 004,020 */ 8, 0x01, 
  /* ABS: 002 Pixels @ 012,020 */ 0, 2, 0x57, 
  /* RLE: 004 Pixels @ 014,020 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 018,020 */ 0, 2, 0x75, 
  /* RLE: 008 Pixels @ 020,020 */ 8, 0x01, 
  /* ABS: 002 Pixels @ 028,020 */ 0, 2, 0x57, 
  /* RLE: 004 Pixels @ 030,020 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 002,021 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 003,021 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 013,021 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 014,021 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 018,021 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 019,021 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 029,021 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 030,021 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 002,022 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 003,022 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 013,022 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 014,022 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 018,022 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 019,022 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 029,022 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 030,022 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 002,023 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 003,023 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 013,023 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 014,023 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 018,023 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 019,023 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 029,023 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 030,023 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 002,024 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 003,024 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 013,024 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 014,024 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 018,024 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 019,024 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 029,024 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 030,024 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 002,025 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 003,025 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 013,025 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 014,025 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 018,025 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 019,025 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 029,025 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 030,025 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 002,026 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 003,026 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 013,026 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 014,026 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 018,026 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 019,026 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 029,026 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 030,026 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 002,027 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 003,027 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 013,027 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 014,027 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 018,027 */ 1, 0x03, 
  /* RLE: 010 Pixels @ 019,027 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 029,027 */ 1, 0x03, 
  /* RLE: 004 Pixels @ 030,027 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 002,028 */ 1, 0x04, 
  /* RLE: 010 Pixels @ 003,028 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 013,028 */ 1, 0x04, 
  /* RLE: 004 Pixels @ 014,028 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 018,028 */ 1, 0x04, 
  /* RLE: 010 Pixels @ 019,028 */ 10, 0x01, 
  /* RLE: 001 Pixels @ 029,028 */ 1, 0x04, 
  /* RLE: 005 Pixels @ 030,028 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 003,029 */ 1, 0x04, 
  /* RLE: 008 Pixels @ 004,029 */ 8, 0x03, 
  /* RLE: 001 Pixels @ 012,029 */ 1, 0x04, 
  /* RLE: 006 Pixels @ 013,029 */ 6, 0x00, 
  /* RLE: 001 Pixels @ 019,029 */ 1, 0x04, 
  /* RLE: 008 Pixels @ 020,029 */ 8, 0x03, 
  /* RLE: 001 Pixels @ 028,029 */ 1, 0x04, 
  /* RLE: 067 Pixels @ 029,029 */ 67, 0x00, 
  0
};  // 321 bytes for 1024 pixels

GUI_CONST_STORAGE GUI_BITMAP bmEthernet_simple_32 = {
  32, // xSize
  32, // ySize
  16, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _acEthernet_simple_32,  // Pointer to picture data (indices)
  &_PalEthernet_simple_32,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
