/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: History_32                                            *
* Dimensions:  32 * 32                                               *
* NumColors:   99                                                    *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmHistory_32;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsHistory_32[] = {
  0xFFFFFF, 0x000000, 0xEFEFEF, 0x7F7F7F,
  0xBFBFBF, 0xFBFBFB, 0x030303, 0x272727,
  0x545454, 0xFCFCFC, 0x0A0A0A, 0x0D0D0D,
  0x2A2A2A, 0xD9D9D9, 0x050505, 0x323232,
  0x464646, 0x636363, 0x6E6E6E, 0x9C9C9C,
  0xB9B9B9, 0xC1C1C1, 0xD3D3D3, 0x010101,
  0x080808, 0x111111, 0x161616, 0x1C1C1C,
  0x202020, 0x373737, 0x383838, 0x3F3F3F,
  0x404040, 0x434343, 0x4B4B4B, 0x4F4F4F,
  0x5A5A5A, 0x5C5C5C, 0x676767, 0x6A6A6A,
  0x6B6B6B, 0x727272, 0x767676, 0x818181,
  0x828282, 0x848484, 0x8F8F8F, 0x999999,
  0xA4A4A4, 0xB4B4B4, 0xB5B5B5, 0xBCBCBC,
  0xCECECE, 0xD5D5D5, 0xD6D6D6, 0xDADADA,
  0xE7E7E7, 0xEAEAEA, 0xEEEEEE, 0xF6F6F6,
  0xF8F8F8, 0xFDFDFD, 0x0F0F0F, 0x121212,
  0x141414, 0x171717, 0x1A1A1A, 0x1B1B1B,
  0x3B3B3B, 0x474747, 0x4E4E4E, 0x646464,
  0x747474, 0x808080, 0x969696, 0x989898,
  0x9B9B9B, 0x9D9D9D, 0x9F9F9F, 0xA6A6A6,
  0xAAAAAA, 0xB6B6B6, 0xB7B7B7, 0xBDBDBD,
  0xCBCBCB, 0xCFCFCF, 0xD1D1D1, 0xD2D2D2,
  0xD8D8D8, 0xDCDCDC, 0xDEDEDE, 0xE0E0E0,
  0xE1E1E1, 0xE2E2E2, 0xE3E3E3, 0xE9E9E9,
  0xF3F3F3, 0xF9F9F9, 0xFEFEFE
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalHistory_32 = {
  99,  // Number of entries
  1,   // Has transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acHistory_32[] = {
  /* RLE: 078 Pixels @ 000,000 */ 78, 0x00, 
  /* ABS: 009 Pixels @ 014,002 */ 0, 9, 0x5B, 0x4A, 0x2A, 0x25, 0x23, 0x26, 0x2C, 0x32, 0x3C, 
  /* RLE: 020 Pixels @ 023,002 */ 20, 0x00, 
  /* ABS: 003 Pixels @ 011,003 */ 0, 3, 0x09, 0x13, 0x0F, 
  /* RLE: 008 Pixels @ 014,003 */ 8, 0x01, 
  /* ABS: 003 Pixels @ 022,003 */ 0, 3, 0x0B, 0x24, 0x35, 
  /* RLE: 017 Pixels @ 025,003 */ 17, 0x00, 
  /* ABS: 002 Pixels @ 010,004 */ 0, 2, 0x33, 0x0C, 
  /* RLE: 012 Pixels @ 012,004 */ 12, 0x01, 
  /* ABS: 003 Pixels @ 024,004 */ 0, 3, 0x06, 0x11, 0x02, 
  /* RLE: 014 Pixels @ 027,004 */ 14, 0x00, 
  /* ABS: 002 Pixels @ 009,005 */ 0, 2, 0x2E, 0x06, 
  /* RLE: 004 Pixels @ 011,005 */ 4, 0x01, 
  /* ABS: 007 Pixels @ 015,005 */ 0, 7, 0x1B, 0x46, 0x49, 0x2F, 0x28, 0x1E, 0x0A, 
  /* RLE: 004 Pixels @ 022,005 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 026,005 */ 0, 2, 0x07, 0x37, 
  /* RLE: 012 Pixels @ 028,005 */ 12, 0x00, 
  /* RLE: 001 Pixels @ 008,006 */ 1, 0x48, 
  /* RLE: 004 Pixels @ 009,006 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 013,006 */ 0, 2, 0x27, 0x5F, 
  /* RLE: 006 Pixels @ 015,006 */ 6, 0x00, 
  /* ABS: 008 Pixels @ 021,006 */ 0, 8, 0x09, 0x15, 0x07, 0x01, 0x01, 0x01, 0x19, 0x16, 
  /* RLE: 010 Pixels @ 029,006 */ 10, 0x00, 
  /* ABS: 006 Pixels @ 007,007 */ 0, 6, 0x4C, 0x01, 0x01, 0x01, 0x1B, 0x14, 
  /* RLE: 010 Pixels @ 013,007 */ 10, 0x00, 
  /* ABS: 007 Pixels @ 023,007 */ 0, 7, 0x3B, 0x12, 0x17, 0x01, 0x01, 0x1C, 0x39, 
  /* RLE: 008 Pixels @ 030,007 */ 8, 0x00, 
  /* ABS: 006 Pixels @ 006,008 */ 0, 6, 0x56, 0x0E, 0x01, 0x01, 0x1F, 0x02, 
  /* RLE: 013 Pixels @ 012,008 */ 13, 0x00, 
  /* ABS: 005 Pixels @ 025,008 */ 0, 5, 0x14, 0x0E, 0x01, 0x01, 0x10, 
  /* RLE: 008 Pixels @ 030,008 */ 8, 0x00, 
  /* ABS: 005 Pixels @ 006,009 */ 0, 5, 0x45, 0x01, 0x01, 0x3E, 0x5E, 
  /* RLE: 005 Pixels @ 011,009 */ 5, 0x00, 
  /* ABS: 004 Pixels @ 016,009 */ 0, 4, 0x61, 0x38, 0x38, 0x62, 
  /* RLE: 006 Pixels @ 020,009 */ 6, 0x00, 
  /* ABS: 005 Pixels @ 026,009 */ 0, 5, 0x2D, 0x01, 0x01, 0x01, 0x31, 
  /* RLE: 006 Pixels @ 031,009 */ 6, 0x00, 
  /* ABS: 005 Pixels @ 005,010 */ 0, 5, 0x15, 0x01, 0x01, 0x01, 0x4E, 
  /* RLE: 006 Pixels @ 010,010 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 016,010 */ 0, 4, 0x04, 0x01, 0x01, 0x02, 
  /* RLE: 006 Pixels @ 020,010 */ 6, 0x00, 
  /* ABS: 005 Pixels @ 026,010 */ 0, 5, 0x09, 0x1D, 0x01, 0x01, 0x0C, 
  /* RLE: 006 Pixels @ 031,010 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 005,011 */ 0, 4, 0x47, 0x01, 0x01, 0x22, 
  /* RLE: 007 Pixels @ 009,011 */ 7, 0x00, 
  /* ABS: 004 Pixels @ 016,011 */ 0, 4, 0x04, 0x01, 0x01, 0x02, 
  /* RLE: 007 Pixels @ 020,011 */ 7, 0x00, 
  /* ABS: 005 Pixels @ 027,011 */ 0, 5, 0x0D, 0x18, 0x01, 0x01, 0x34, 
  /* RLE: 004 Pixels @ 000,012 */ 4, 0x00, 
  /* ABS: 005 Pixels @ 004,012 */ 0, 5, 0x3D, 0x1A, 0x01, 0x01, 0x50, 
  /* RLE: 007 Pixels @ 009,012 */ 7, 0x00, 
  /* ABS: 004 Pixels @ 016,012 */ 0, 4, 0x04, 0x01, 0x01, 0x02, 
  /* RLE: 008 Pixels @ 020,012 */ 8, 0x00, 
  /* ABS: 004 Pixels @ 028,012 */ 0, 4, 0x20, 0x01, 0x01, 0x2B, 
  /* RLE: 004 Pixels @ 000,013 */ 4, 0x00, 
  /* ABS: 005 Pixels @ 004,013 */ 0, 5, 0x16, 0x01, 0x01, 0x01, 0x5A, 
  /* RLE: 007 Pixels @ 009,013 */ 7, 0x00, 
  /* ABS: 004 Pixels @ 016,013 */ 0, 4, 0x04, 0x01, 0x01, 0x02, 
  /* RLE: 008 Pixels @ 020,013 */ 8, 0x00, 
  /* ABS: 004 Pixels @ 028,013 */ 0, 4, 0x29, 0x01, 0x01, 0x21, 
  /* RLE: 004 Pixels @ 000,014 */ 4, 0x00, 
  /* ABS: 004 Pixels @ 004,014 */ 0, 4, 0x52, 0x01, 0x01, 0x3F, 
  /* RLE: 008 Pixels @ 008,014 */ 8, 0x00, 
  /* ABS: 004 Pixels @ 016,014 */ 0, 4, 0x04, 0x01, 0x01, 0x02, 
  /* RLE: 008 Pixels @ 020,014 */ 8, 0x00, 
  /* ABS: 004 Pixels @ 028,014 */ 0, 4, 0x30, 0x01, 0x01, 0x07, 
  /* RLE: 004 Pixels @ 000,015 */ 4, 0x00, 
  /* ABS: 004 Pixels @ 004,015 */ 0, 4, 0x4D, 0x01, 0x01, 0x10, 
  /* RLE: 008 Pixels @ 008,015 */ 8, 0x00, 
  /* ABS: 004 Pixels @ 016,015 */ 0, 4, 0x04, 0x01, 0x01, 0x02, 
  /* RLE: 008 Pixels @ 020,015 */ 8, 0x00, 
  /* ABS: 005 Pixels @ 028,015 */ 0, 5, 0x36, 0x01, 0x01, 0x0B, 0x03, 
  /* RLE: 010 Pixels @ 001,016 */ 10, 0x01, 
  /* ABS: 009 Pixels @ 011,016 */ 0, 9, 0x08, 0x05, 0x00, 0x00, 0x00, 0x04, 0x01, 0x01, 0x13, 
  /* RLE: 008 Pixels @ 020,016 */ 8, 0x00, 
  /* ABS: 006 Pixels @ 028,016 */ 0, 6, 0x36, 0x01, 0x01, 0x0B, 0x00, 0x03, 
  /* RLE: 008 Pixels @ 002,017 */ 8, 0x01, 
  /* ABS: 002 Pixels @ 010,017 */ 0, 2, 0x08, 0x05, 
  /* RLE: 004 Pixels @ 012,017 */ 4, 0x00, 
  /* ABS: 006 Pixels @ 016,017 */ 0, 6, 0x0D, 0x1A, 0x01, 0x01, 0x44, 0x55, 
  /* RLE: 006 Pixels @ 022,017 */ 6, 0x00, 
  /* ABS: 007 Pixels @ 028,017 */ 0, 7, 0x30, 0x01, 0x01, 0x07, 0x00, 0x00, 0x03, 
  /* RLE: 006 Pixels @ 003,018 */ 6, 0x01, 
  /* ABS: 002 Pixels @ 009,018 */ 0, 2, 0x08, 0x05, 
  /* RLE: 006 Pixels @ 011,018 */ 6, 0x00, 
  /* ABS: 007 Pixels @ 017,018 */ 0, 7, 0x02, 0x12, 0x06, 0x01, 0x06, 0x27, 0x3A, 
  /* RLE: 004 Pixels @ 024,018 */ 4, 0x00, 
  /* ABS: 008 Pixels @ 028,018 */ 0, 8, 0x29, 0x01, 0x01, 0x21, 0x00, 0x00, 0x00, 0x03, 
  /* RLE: 004 Pixels @ 004,019 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 008,019 */ 0, 2, 0x08, 0x05, 
  /* RLE: 009 Pixels @ 010,019 */ 9, 0x00, 
  /* ABS: 013 Pixels @ 019,019 */ 0, 13, 0x57, 0x1F, 0x01, 0x01, 0x40, 0x58, 0x00, 0x00, 0x00, 0x20, 0x01, 0x01, 0x2B, 
  /* RLE: 004 Pixels @ 000,020 */ 4, 0x00, 
  /* ABS: 005 Pixels @ 004,020 */ 0, 5, 0x03, 0x01, 0x01, 0x08, 0x05, 
  /* RLE: 012 Pixels @ 009,020 */ 12, 0x00, 
  /* ABS: 011 Pixels @ 021,020 */ 0, 11, 0x4F, 0x43, 0x0F, 0x3D, 0x00, 0x00, 0x0D, 0x18, 0x01, 0x01, 0x34, 
  /* RLE: 005 Pixels @ 000,021 */ 5, 0x00, 
  /* ABS: 003 Pixels @ 005,021 */ 0, 3, 0x03, 0x08, 0x05, 
  /* RLE: 014 Pixels @ 008,021 */ 14, 0x00, 
  /* ABS: 009 Pixels @ 022,021 */ 0, 9, 0x60, 0x59, 0x00, 0x00, 0x09, 0x1D, 0x01, 0x01, 0x0C, 
  /* RLE: 007 Pixels @ 031,021 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 006,022 */ 1, 0x05, 
  /* RLE: 019 Pixels @ 007,022 */ 19, 0x00, 
  /* ABS: 005 Pixels @ 026,022 */ 0, 5, 0x2D, 0x01, 0x01, 0x01, 0x31, 
  /* RLE: 011 Pixels @ 031,022 */ 11, 0x00, 
  /* ABS: 002 Pixels @ 010,023 */ 0, 2, 0x54, 0x3A, 
  /* RLE: 013 Pixels @ 012,023 */ 13, 0x00, 
  /* ABS: 005 Pixels @ 025,023 */ 0, 5, 0x14, 0x0E, 0x01, 0x01, 0x10, 
  /* RLE: 011 Pixels @ 030,023 */ 11, 0x00, 
  /* ABS: 004 Pixels @ 009,024 */ 0, 4, 0x53, 0x0A, 0x42, 0x51, 
  /* RLE: 010 Pixels @ 013,024 */ 10, 0x00, 
  /* ABS: 007 Pixels @ 023,024 */ 0, 7, 0x3B, 0x12, 0x17, 0x01, 0x01, 0x1C, 0x39, 
  /* RLE: 010 Pixels @ 030,024 */ 10, 0x00, 
  /* ABS: 007 Pixels @ 008,025 */ 0, 7, 0x0D, 0x0A, 0x01, 0x01, 0x01, 0x11, 0x5D, 
  /* RLE: 006 Pixels @ 015,025 */ 6, 0x00, 
  /* ABS: 008 Pixels @ 021,025 */ 0, 8, 0x09, 0x15, 0x07, 0x01, 0x01, 0x01, 0x19, 0x16, 
  /* RLE: 012 Pixels @ 029,025 */ 12, 0x00, 
  /* ABS: 002 Pixels @ 009,026 */ 0, 2, 0x2E, 0x06, 
  /* RLE: 004 Pixels @ 011,026 */ 4, 0x01, 
  /* ABS: 007 Pixels @ 015,026 */ 0, 7, 0x41, 0x22, 0x03, 0x2F, 0x28, 0x1E, 0x0A, 
  /* RLE: 004 Pixels @ 022,026 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 026,026 */ 0, 2, 0x07, 0x37, 
  /* RLE: 014 Pixels @ 028,026 */ 14, 0x00, 
  /* ABS: 002 Pixels @ 010,027 */ 0, 2, 0x33, 0x0C, 
  /* RLE: 012 Pixels @ 012,027 */ 12, 0x01, 
  /* ABS: 003 Pixels @ 024,027 */ 0, 3, 0x06, 0x11, 0x02, 
  /* RLE: 016 Pixels @ 027,027 */ 16, 0x00, 
  /* ABS: 003 Pixels @ 011,028 */ 0, 3, 0x09, 0x13, 0x0F, 
  /* RLE: 008 Pixels @ 014,028 */ 8, 0x01, 
  /* ABS: 003 Pixels @ 022,028 */ 0, 3, 0x0B, 0x24, 0x35, 
  /* RLE: 021 Pixels @ 025,028 */ 21, 0x00, 
  /* ABS: 009 Pixels @ 014,029 */ 0, 9, 0x5C, 0x4B, 0x2A, 0x25, 0x23, 0x26, 0x2C, 0x32, 0x3C, 
  /* RLE: 073 Pixels @ 023,029 */ 73, 0x00, 
  0
};  // 582 bytes for 1024 pixels

GUI_CONST_STORAGE GUI_BITMAP bmHistory_32 = {
  32, // xSize
  32, // ySize
  32, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  _acHistory_32,  // Pointer to picture data (indices)
  &_PalHistory_32,  // Pointer to palette
  GUI_DRAW_RLE8
};

/*************************** End of file ****************************/
