/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "WM.h"
#include "DIALOG.h"

#include "ViewContainer/ViewNavigator.h"
#include "MemoryDataContext.h"

#include "Contact.h"

#include "ViewContainer/ListView.h"
#include "ViewContainer/OptionListView.h"
#include "ViewContainer/EditView.h"
#include "ViewContainer/InfoView.h"

#include "Api/V25TER.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_02     (GUI_ID_USER + 0x10)
#define ID_LISTBOX_0     (GUI_ID_USER + 0x11)

extern GUI_CONST_STORAGE GUI_BITMAP bmphonecall;
extern GUI_CONST_STORAGE GUI_BITMAP bmpencil;
extern GUI_CONST_STORAGE GUI_BITMAP bmloupe;
extern GUI_CONST_STORAGE GUI_BITMAP bmdelete;



void InitContactView(void);
static void CallFunctionCallback(void);
static void ContactEditFunctionCallback(void);
static void ContactViewFunctionCallBcak(void);
static void ContactDeleteFunctionCallback(void);
static void ContactAddFunctionCallback(void);
static void ContactEditFinishedCallback(void *);
static void ContactEditCancelCallback(void *);
static void ContactSelectCallback(void);

extern ListApiHandlers_typedef ContactListApiHandlers;



extern View_Typedef ListView;
extern View_Typedef EditView;
extern View_Typedef OptionListView;
extern View_Typedef InfoView;




static const CustomFunction_Typedef AddFunction = { NULL,
		(const char*) "Add New...",
		ContactAddFunctionCallback };
static const CustomFunction_Typedef * ContactListFunctionList[2] =
		{ &AddFunction, NULL };
static ListView_Parameters_Typedef Contact_ListView_Parameters = { //
		ContactListFunctionList, // custom function list
				&ContactListApiHandlers,  // list api handler
				ContactSelectCallback, // list select callback
				0, // not document
				0 // not document
		};





static const CustomFunction_Typedef CallFunction = { &bmphonecall,
		(const char*) "Call", CallFunctionCallback };
static const CustomFunction_Typedef EditFunction = { &bmpencil,
		(const char*) "Edit",
		ContactEditFunctionCallback };
static const CustomFunction_Typedef ViewInfoFunction = { &bmloupe,
		(const char*) "View",
		ContactViewFunctionCallBcak };
static const CustomFunction_Typedef DeleteFunction = { &bmdelete,
		(const char*) "Delete",
		ContactDeleteFunctionCallback };
const CustomFunction_Typedef * ContactOptionFunctionList[] = { &CallFunction,
		&EditFunction, &ViewInfoFunction, &DeleteFunction, NULL };
static OptionListView_Parameters_Typedef ContactOptionListView_Parameters = { //
		ContactOptionFunctionList, // custom function list
				0, // option select callback
				0, // not document
		};



static EditView_Parameters_Typedef ContactEditView_Parameters = { //
		&ContactFieldsAttribute, //
				ContactEditFinishedCallback, // Finished Edit Callback
				ContactEditCancelCallback, // Canceled Edit Callback
				CONTACT_FIELD_COUNT, // Number of contact model field
				0, //
				0, //
				0, //
		};

static InfoView_Parameters_Typedef ContactInfoView_Parameters = { //
		&ContactListApiHandlers // list api handler
		};


void InitContactView() {

	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &ListView,
			&Contact_ListView_Parameters);
}

void ContactEditFunctionCallback() {
	ContactEditView_Parameters.isNew = 0;
	ContactEditView_Parameters.editableModel =
			ContactListApiHandlers.GetSelectedItem();
	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &EditView,
			&ContactEditView_Parameters);
}

void ContactViewFunctionCallBcak() {
	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &InfoView,
			&ContactInfoView_Parameters);
}

void ContactDeleteFunctionCallback() {
	ContactListApiHandlers.RemoveCurrent();
	ViewNavigator_GoBackView(&DefaultViewNavigator);
}
void ContactAddFunctionCallback() {
	ContactEditView_Parameters.isNew = 1;
	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &EditView,
			&ContactEditView_Parameters);

}
static void CallFunctionCallback(void) {
	Contact_Typedef *contact = ContactListApiHandlers.GetSelectedItem();
	char num[20];
	strcpy(num, contact->CallNumber);
	strcat(num, ";");
	GSM_CALL_TO_DIAL_A_NUMBER(num);
}

void ContactSelectCallback(void) {
	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &OptionListView,
			&ContactOptionListView_Parameters);
}
void ContactEditFinishedCallback(void * parameters) {
	EditView_Parameters_Typedef *param =
			(EditView_Parameters_Typedef *) parameters;

	Contact_Typedef *newContact = CreateContact(
			((Contact_Typedef*) (param->buffer))->Name,
			((Contact_Typedef*) (param->buffer))->CallNumber);
	if (param->isNew == 1)
		ContactListApiHandlers.Add(newContact);
	else
	{
		ContactListApiHandlers.Edit(param->editableModel, newContact);
		FreeContact(param->editableModel);
	}
	FreeContact(newContact);
}
void ContactEditCancelCallback(void *parameters) {
	EditView_Parameters_Typedef *param =
			(EditView_Parameters_Typedef *) parameters;
	if (param->isNew == 0)
		FreeContact(param->editableModel);

}
// USER END

/*************************** End of file ****************************/
