/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: capacitor_simple_32                                   *
* Dimensions:  32 * 32                                               *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmcapacitor_simple_32;

#if 0

/*********************************************************************
 *
 *  This palette is included for reference only
 *  As it is saved as device dependent bitmap without color info.
 *  Please note that this bitmap requires the physical palette to be
 *  identical to the palette of the display.
 *  If this does not work out, please convert your bitmap into a DIB
 */
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorscapacitor_simple_32[] = {
  0xFDFDFD, 0x616161, 0xA6A6A6, 0x040404
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palcapacitor_simple_32 = {
  4,  // Number of entries
  1,  // Has transparency
		NULL
};

static GUI_CONST_STORAGE unsigned char _accapacitor_simple_32[] = {
/* RLE: 020 Pixels @ 000,000 */20, 0x00,
/* RLE: 001 Pixels @ 020,000 */1, 0x02,
/* RLE: 029 Pixels @ 021,000 */29, 0x00,
/* ABS: 005 Pixels @ 018,001 */0, 5, 0x23, 0x33, 0x10,
/* RLE: 026 Pixels @ 023,001 */26, 0x00,
/* ABS: 007 Pixels @ 017,002 */0, 7, 0x23, 0x32, 0x01, 0x10,
/* RLE: 024 Pixels @ 024,002 */24, 0x00,
/* ABS: 010 Pixels @ 016,003 */0, 10, 0x23, 0x33, 0x10, 0x02, 0x32,
/* RLE: 021 Pixels @ 026,003 */21, 0x00,
/* RLE: 001 Pixels @ 015,004 */1, 0x02,
/* RLE: 005 Pixels @ 016,004 */5, 0x03,
/* ABS: 006 Pixels @ 021,004 */0, 6, 0x20, 0x02, 0x31,
/* RLE: 019 Pixels @ 027,004 */19, 0x00,
/* RLE: 001 Pixels @ 014,005 */1, 0x02,
/* RLE: 007 Pixels @ 015,005 */7, 0x03,
/* ABS: 006 Pixels @ 022,005 */0, 6, 0x20, 0x00, 0x11,
/* RLE: 017 Pixels @ 028,005 */17, 0x00,
/* RLE: 001 Pixels @ 013,006 */1, 0x02,
/* RLE: 009 Pixels @ 014,006 */9, 0x03,
/* RLE: 004 Pixels @ 023,006 */4, 0x00,
/* ABS: 002 Pixels @ 027,006 */0, 2, 0x32,
/* RLE: 015 Pixels @ 029,006 */15, 0x00,
/* RLE: 001 Pixels @ 012,007 */1, 0x02,
/* RLE: 011 Pixels @ 013,007 */11, 0x03,
/* RLE: 004 Pixels @ 024,007 */4, 0x00,
/* ABS: 002 Pixels @ 028,007 */0, 2, 0x32,
/* RLE: 013 Pixels @ 030,007 */13, 0x00,
/* RLE: 001 Pixels @ 011,008 */1, 0x02,
/* RLE: 012 Pixels @ 012,008 */12, 0x03,
/* ABS: 006 Pixels @ 024,008 */0, 6, 0x10, 0x00, 0x23,
/* RLE: 012 Pixels @ 030,008 */12, 0x00,
/* RLE: 001 Pixels @ 010,009 */1, 0x02,
/* RLE: 015 Pixels @ 011,009 */15, 0x03,
/* RLE: 003 Pixels @ 026,009 */3, 0x00,
/* ABS: 002 Pixels @ 029,009 */0, 2, 0x21,
/* RLE: 010 Pixels @ 031,009 */10, 0x00,
/* RLE: 001 Pixels @ 009,010 */1, 0x02,
/* RLE: 017 Pixels @ 010,010 */17, 0x03,
/* ABS: 005 Pixels @ 027,010 */0, 5, 0x20, 0x01, 0x20,
/* RLE: 008 Pixels @ 000,011 */8, 0x00,
/* RLE: 001 Pixels @ 008,011 */1, 0x02,
/* RLE: 019 Pixels @ 009,011 */19, 0x03,
/* ABS: 004 Pixels @ 028,011 */0, 4, 0x10, 0x21,
/* RLE: 008 Pixels @ 000,012 */8, 0x00,
/* RLE: 001 Pixels @ 008,012 */1, 0x02,
/* RLE: 023 Pixels @ 009,012 */23, 0x03,
/* RLE: 009 Pixels @ 000,013 */9, 0x00,
/* RLE: 022 Pixels @ 009,013 */22, 0x03,
/* RLE: 001 Pixels @ 031,013 */1, 0x01,
/* RLE: 009 Pixels @ 000,014 */9, 0x00,
/* RLE: 001 Pixels @ 009,014 */1, 0x01,
/* RLE: 020 Pixels @ 010,014 */20, 0x03,
/* RLE: 001 Pixels @ 030,014 */1, 0x01,
/* RLE: 009 Pixels @ 031,014 */9, 0x00,
/* RLE: 001 Pixels @ 008,015 */1, 0x02,
/* RLE: 020 Pixels @ 009,015 */20, 0x03,
/* RLE: 001 Pixels @ 029,015 */1, 0x01,
/* RLE: 009 Pixels @ 030,015 */9, 0x00,
/* RLE: 001 Pixels @ 007,016 */1, 0x02,
/* RLE: 020 Pixels @ 008,016 */20, 0x03,
/* RLE: 001 Pixels @ 028,016 */1, 0x01,
/* RLE: 009 Pixels @ 029,016 */9, 0x00,
/* ABS: 006 Pixels @ 006,017 */0, 6, 0x13, 0x33, 0x21,
/* RLE: 015 Pixels @ 012,017 */15, 0x03,
/* RLE: 001 Pixels @ 027,017 */1, 0x01,
/* RLE: 009 Pixels @ 028,017 */9, 0x00,
/* ABS: 008 Pixels @ 005,018 */0, 8, 0x13, 0x33, 0x20, 0x01,
/* RLE: 013 Pixels @ 013,018 */13, 0x03,
/* RLE: 001 Pixels @ 026,018 */1, 0x01,
/* RLE: 009 Pixels @ 027,018 */9, 0x00,
/* RLE: 003 Pixels @ 004,019 */3, 0x03,
/* RLE: 001 Pixels @ 007,019 */1, 0x01,
/* RLE: 005 Pixels @ 008,019 */5, 0x00,
/* RLE: 001 Pixels @ 013,019 */1, 0x01,
/* RLE: 011 Pixels @ 014,019 */11, 0x03,
/* RLE: 001 Pixels @ 025,019 */1, 0x01,
/* RLE: 008 Pixels @ 026,019 */8, 0x00,
/* ABS: 005 Pixels @ 002,020 */0, 5, 0x23, 0x33, 0x10,
/* RLE: 007 Pixels @ 007,020 */7, 0x00,
/* RLE: 001 Pixels @ 014,020 */1, 0x01,
/* RLE: 009 Pixels @ 015,020 */9, 0x03,
/* RLE: 001 Pixels @ 024,020 */1, 0x01,
/* RLE: 008 Pixels @ 025,020 */8, 0x00,
/* ABS: 005 Pixels @ 001,021 */0, 5, 0x23, 0x33, 0x20,
/* RLE: 009 Pixels @ 006,021 */9, 0x00,
/* RLE: 001 Pixels @ 015,021 */1, 0x01,
/* RLE: 007 Pixels @ 016,021 */7, 0x03,
/* RLE: 001 Pixels @ 023,021 */1, 0x01,
/* RLE: 008 Pixels @ 024,021 */8, 0x00,
/* ABS: 005 Pixels @ 000,022 */0, 5, 0x13, 0x33, 0x20,
/* RLE: 010 Pixels @ 005,022 */10, 0x00,
/* RLE: 001 Pixels @ 015,022 */1, 0x02,
/* RLE: 006 Pixels @ 016,022 */6, 0x03,
/* RLE: 001 Pixels @ 022,022 */1, 0x01,
/* RLE: 009 Pixels @ 023,022 */9, 0x00,
/* RLE: 003 Pixels @ 000,023 */3, 0x03,
/* RLE: 011 Pixels @ 003,023 */11, 0x00,
/* ABS: 008 Pixels @ 014,023 */0, 8, 0x23, 0x33, 0x11, 0x31,
/* RLE: 010 Pixels @ 022,023 */10, 0x00,
/* ABS: 002 Pixels @ 000,024 */0, 2, 0x21,
/* RLE: 012 Pixels @ 002,024 */12, 0x00,
/* RLE: 003 Pixels @ 014,024 */3, 0x03,
/* RLE: 001 Pixels @ 017,024 */1, 0x02,
/* RLE: 027 Pixels @ 018,024 */27, 0x00,
/* RLE: 003 Pixels @ 013,025 */3, 0x03,
/* RLE: 001 Pixels @ 016,025 */1, 0x02,
/* RLE: 027 Pixels @ 017,025 */27, 0x00,
/* RLE: 003 Pixels @ 012,026 */3, 0x03,
/* RLE: 001 Pixels @ 015,026 */1, 0x02,
/* RLE: 027 Pixels @ 016,026 */27, 0x00,
/* ABS: 004 Pixels @ 011,027 */0, 4, 0x13, 0x31,
/* RLE: 027 Pixels @ 015,027 */27, 0x00,
/* ABS: 004 Pixels @ 010,028 */0, 4, 0x13, 0x31,
/* RLE: 027 Pixels @ 014,028 */27, 0x00,
/* ABS: 004 Pixels @ 009,029 */0, 4, 0x23, 0x31,
/* RLE: 028 Pixels @ 013,029 */28, 0x00,
/* ABS: 003 Pixels @ 009,030 */0, 3, 0x13, 0x10,
/* RLE: 030 Pixels @ 012,030 */30, 0x00,
/* RLE: 001 Pixels @ 010,031 */1, 0x02,
/* RLE: 021 Pixels @ 011,031 */21, 0x00, 0 };  // 298 bytes for 1024 pixels

GUI_CONST_STORAGE GUI_BITMAP bmcapacitor_simple_32 = {
  32, // xSize
  32, // ySize
		16, // BytesPerLine
		GUI_COMPRESS_RLE4, // BitsPerPixel
  _accapacitor_simple_32,  // Pointer to picture data (indices)
		&_Palcapacitor_simple_32,  // Pointer to palette
		GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
