/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Setting_simple_32                                     *
* Dimensions:  32 * 32                                               *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmSetting_simple_32;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsSetting_simple_32[] = {
  0xFCFCFC, 0x5D5D5D, 0x999999, 0x030303
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalSetting_simple_32 = {
  4,  // Number of entries
  1,  // Has transparency
  &_ColorsSetting_simple_32[0]
};

static GUI_CONST_STORAGE unsigned char _acSetting_simple_32[] = {
  /* RLE: 014 Pixels @ 000,000 */ 14, 0x00, 
  /* RLE: 004 Pixels @ 014,000 */ 4, 0x03, 
  /* RLE: 001 Pixels @ 018,000 */ 1, 0x02, 
  /* RLE: 026 Pixels @ 019,000 */ 26, 0x00, 
  /* RLE: 001 Pixels @ 013,001 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 014,001 */ 4, 0x03, 
  /* RLE: 001 Pixels @ 018,001 */ 1, 0x01, 
  /* RLE: 026 Pixels @ 019,001 */ 26, 0x00, 
  /* RLE: 006 Pixels @ 013,002 */ 6, 0x03, 
  /* RLE: 019 Pixels @ 019,002 */ 19, 0x00, 
  /* ABS: 002 Pixels @ 006,003 */ 0, 2, 0x12, 
  /* RLE: 004 Pixels @ 008,003 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 012,003 */ 1, 0x01, 
  /* RLE: 006 Pixels @ 013,003 */ 6, 0x03, 
  /* RLE: 001 Pixels @ 019,003 */ 1, 0x01, 
  /* RLE: 005 Pixels @ 020,003 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 025,003 */ 1, 0x02, 
  /* RLE: 011 Pixels @ 026,003 */ 11, 0x00, 
  /* RLE: 003 Pixels @ 005,004 */ 3, 0x03, 
  /* ABS: 004 Pixels @ 008,004 */ 0, 4, 0x12, 0x11, 
  /* RLE: 008 Pixels @ 012,004 */ 8, 0x03, 
  /* ABS: 007 Pixels @ 020,004 */ 0, 7, 0x12, 0x21, 0x33, 0x30, 
  /* RLE: 009 Pixels @ 027,004 */ 9, 0x00, 
  /* RLE: 024 Pixels @ 004,005 */ 24, 0x03, 
  /* RLE: 007 Pixels @ 028,005 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 003,006 */ 1, 0x02, 
  /* RLE: 024 Pixels @ 004,006 */ 24, 0x03, 
  /* RLE: 001 Pixels @ 028,006 */ 1, 0x02, 
  /* RLE: 007 Pixels @ 029,006 */ 7, 0x00, 
  /* RLE: 024 Pixels @ 004,007 */ 24, 0x03, 
  /* RLE: 001 Pixels @ 028,007 */ 1, 0x02, 
  /* RLE: 007 Pixels @ 029,007 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 004,008 */ 1, 0x01, 
  /* RLE: 022 Pixels @ 005,008 */ 22, 0x03, 
  /* RLE: 001 Pixels @ 027,008 */ 1, 0x01, 
  /* RLE: 008 Pixels @ 028,008 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 004,009 */ 1, 0x02, 
  /* RLE: 022 Pixels @ 005,009 */ 22, 0x03, 
  /* RLE: 001 Pixels @ 027,009 */ 1, 0x02, 
  /* RLE: 008 Pixels @ 028,009 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 004,010 */ 1, 0x02, 
  /* RLE: 010 Pixels @ 005,010 */ 10, 0x03, 
  /* ABS: 002 Pixels @ 015,010 */ 0, 2, 0x11, 
  /* RLE: 010 Pixels @ 017,010 */ 10, 0x03, 
  /* RLE: 001 Pixels @ 027,010 */ 1, 0x02, 
  /* RLE: 008 Pixels @ 028,010 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 004,011 */ 1, 0x01, 
  /* RLE: 008 Pixels @ 005,011 */ 8, 0x03, 
  /* RLE: 001 Pixels @ 013,011 */ 1, 0x02, 
  /* RLE: 004 Pixels @ 014,011 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 018,011 */ 1, 0x02, 
  /* RLE: 008 Pixels @ 019,011 */ 8, 0x03, 
  /* RLE: 001 Pixels @ 027,011 */ 1, 0x01, 
  /* RLE: 007 Pixels @ 028,011 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 003,012 */ 1, 0x01, 
  /* RLE: 008 Pixels @ 004,012 */ 8, 0x03, 
  /* RLE: 008 Pixels @ 012,012 */ 8, 0x00, 
  /* RLE: 008 Pixels @ 020,012 */ 8, 0x03, 
  /* ABS: 006 Pixels @ 028,012 */ 0, 6, 0x10, 0x00, 0x21, 
  /* RLE: 009 Pixels @ 002,013 */ 9, 0x03, 
  /* RLE: 001 Pixels @ 011,013 */ 1, 0x02, 
  /* RLE: 008 Pixels @ 012,013 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 020,013 */ 1, 0x02, 
  /* RLE: 009 Pixels @ 021,013 */ 9, 0x03, 
  /* ABS: 002 Pixels @ 030,013 */ 0, 2, 0x10, 
  /* RLE: 011 Pixels @ 000,014 */ 11, 0x03, 
  /* RLE: 010 Pixels @ 011,014 */ 10, 0x00, 
  /* RLE: 021 Pixels @ 021,014 */ 21, 0x03, 
  /* RLE: 001 Pixels @ 010,015 */ 1, 0x01, 
  /* RLE: 010 Pixels @ 011,015 */ 10, 0x00, 
  /* RLE: 001 Pixels @ 021,015 */ 1, 0x01, 
  /* RLE: 020 Pixels @ 022,015 */ 20, 0x03, 
  /* RLE: 001 Pixels @ 010,016 */ 1, 0x01, 
  /* RLE: 010 Pixels @ 011,016 */ 10, 0x00, 
  /* RLE: 001 Pixels @ 021,016 */ 1, 0x01, 
  /* RLE: 021 Pixels @ 022,016 */ 21, 0x03, 
  /* RLE: 010 Pixels @ 011,017 */ 10, 0x00, 
  /* RLE: 011 Pixels @ 021,017 */ 11, 0x03, 
  /* ABS: 002 Pixels @ 000,018 */ 0, 2, 0x01, 
  /* RLE: 009 Pixels @ 002,018 */ 9, 0x03, 
  /* RLE: 001 Pixels @ 011,018 */ 1, 0x02, 
  /* RLE: 008 Pixels @ 012,018 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 020,018 */ 1, 0x02, 
  /* RLE: 009 Pixels @ 021,018 */ 9, 0x03, 
  /* ABS: 006 Pixels @ 030,018 */ 0, 6, 0x12, 0x00, 0x01, 
  /* RLE: 008 Pixels @ 004,019 */ 8, 0x03, 
  /* RLE: 008 Pixels @ 012,019 */ 8, 0x00, 
  /* RLE: 008 Pixels @ 020,019 */ 8, 0x03, 
  /* RLE: 001 Pixels @ 028,019 */ 1, 0x01, 
  /* RLE: 007 Pixels @ 029,019 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 004,020 */ 1, 0x01, 
  /* RLE: 008 Pixels @ 005,020 */ 8, 0x03, 
  /* RLE: 001 Pixels @ 013,020 */ 1, 0x02, 
  /* RLE: 004 Pixels @ 014,020 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 018,020 */ 1, 0x02, 
  /* RLE: 008 Pixels @ 019,020 */ 8, 0x03, 
  /* RLE: 001 Pixels @ 027,020 */ 1, 0x01, 
  /* RLE: 008 Pixels @ 028,020 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 004,021 */ 1, 0x02, 
  /* RLE: 010 Pixels @ 005,021 */ 10, 0x03, 
  /* ABS: 002 Pixels @ 015,021 */ 0, 2, 0x11, 
  /* RLE: 010 Pixels @ 017,021 */ 10, 0x03, 
  /* RLE: 001 Pixels @ 027,021 */ 1, 0x02, 
  /* RLE: 008 Pixels @ 028,021 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 004,022 */ 1, 0x02, 
  /* RLE: 022 Pixels @ 005,022 */ 22, 0x03, 
  /* RLE: 001 Pixels @ 027,022 */ 1, 0x02, 
  /* RLE: 008 Pixels @ 028,022 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 004,023 */ 1, 0x01, 
  /* RLE: 022 Pixels @ 005,023 */ 22, 0x03, 
  /* RLE: 001 Pixels @ 027,023 */ 1, 0x01, 
  /* RLE: 007 Pixels @ 028,023 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 003,024 */ 1, 0x02, 
  /* RLE: 024 Pixels @ 004,024 */ 24, 0x03, 
  /* RLE: 007 Pixels @ 028,024 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 003,025 */ 1, 0x02, 
  /* RLE: 024 Pixels @ 004,025 */ 24, 0x03, 
  /* RLE: 001 Pixels @ 028,025 */ 1, 0x02, 
  /* RLE: 007 Pixels @ 029,025 */ 7, 0x00, 
  /* RLE: 024 Pixels @ 004,026 */ 24, 0x03, 
  /* RLE: 009 Pixels @ 028,026 */ 9, 0x00, 
  /* RLE: 003 Pixels @ 005,027 */ 3, 0x03, 
  /* ABS: 004 Pixels @ 008,027 */ 0, 4, 0x12, 0x21, 
  /* RLE: 008 Pixels @ 012,027 */ 8, 0x03, 
  /* ABS: 007 Pixels @ 020,027 */ 0, 7, 0x11, 0x21, 0x33, 0x30, 
  /* RLE: 011 Pixels @ 027,027 */ 11, 0x00, 
  /* RLE: 001 Pixels @ 006,028 */ 1, 0x02, 
  /* RLE: 005 Pixels @ 007,028 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 012,028 */ 1, 0x01, 
  /* RLE: 006 Pixels @ 013,028 */ 6, 0x03, 
  /* RLE: 001 Pixels @ 019,028 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 020,028 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 024,028 */ 0, 2, 0x21, 
  /* RLE: 019 Pixels @ 026,028 */ 19, 0x00, 
  /* RLE: 006 Pixels @ 013,029 */ 6, 0x03, 
  /* RLE: 026 Pixels @ 019,029 */ 26, 0x00, 
  /* RLE: 001 Pixels @ 013,030 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 014,030 */ 4, 0x03, 
  /* RLE: 001 Pixels @ 018,030 */ 1, 0x01, 
  /* RLE: 026 Pixels @ 019,030 */ 26, 0x00, 
  /* RLE: 001 Pixels @ 013,031 */ 1, 0x02, 
  /* RLE: 004 Pixels @ 014,031 */ 4, 0x03, 
  /* RLE: 014 Pixels @ 018,031 */ 14, 0x00, 
  0
};  // 310 bytes for 1024 pixels

GUI_CONST_STORAGE GUI_BITMAP bmSetting_simple_32 = {
  32, // xSize
  32, // ySize
  16, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _acSetting_simple_32,  // Pointer to picture data (indices)
  &_PalSetting_simple_32,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
