/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Setup_simple_32                                       *
* Dimensions:  32 * 32                                               *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmSetup_simple_32;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsSetup_simple_32[] = {
  0xFFFFFF, 0x000000, 0x0D0D0D, 0x8D8D8D
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalSetup_simple_32 = {
  4,  // Number of entries
  1,  // Has transparency
  &_ColorsSetup_simple_32[0]
};

static GUI_CONST_STORAGE unsigned char _acSetup_simple_32[] = {
  /* RLE: 070 Pixels @ 000,000 */ 70, 0x00, 
  /* ABS: 002 Pixels @ 006,002 */ 0, 2, 0x32, 
  /* RLE: 004 Pixels @ 008,002 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 012,002 */ 0, 2, 0x23, 
  /* RLE: 024 Pixels @ 014,002 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 006,003 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 007,003 */ 6, 0x01, 
  /* RLE: 001 Pixels @ 013,003 */ 1, 0x02, 
  /* RLE: 018 Pixels @ 014,003 */ 18, 0x00, 
  /* RLE: 008 Pixels @ 000,004 */ 8, 0x01, 
  /* RLE: 004 Pixels @ 008,004 */ 4, 0x00, 
  /* RLE: 028 Pixels @ 012,004 */ 28, 0x01, 
  /* RLE: 004 Pixels @ 008,005 */ 4, 0x00, 
  /* RLE: 028 Pixels @ 012,005 */ 28, 0x01, 
  /* RLE: 004 Pixels @ 008,006 */ 4, 0x00, 
  /* RLE: 028 Pixels @ 012,006 */ 28, 0x01, 
  /* RLE: 004 Pixels @ 008,007 */ 4, 0x00, 
  /* RLE: 020 Pixels @ 012,007 */ 20, 0x01, 
  /* RLE: 006 Pixels @ 000,008 */ 6, 0x00, 
  /* RLE: 001 Pixels @ 006,008 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 007,008 */ 6, 0x01, 
  /* RLE: 001 Pixels @ 013,008 */ 1, 0x02, 
  /* RLE: 024 Pixels @ 014,008 */ 24, 0x00, 
  /* ABS: 002 Pixels @ 006,009 */ 0, 2, 0x32, 
  /* RLE: 004 Pixels @ 008,009 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 012,009 */ 0, 2, 0x23, 
  /* RLE: 100 Pixels @ 014,009 */ 100, 0x00, 
  /* ABS: 002 Pixels @ 018,012 */ 0, 2, 0x32, 
  /* RLE: 004 Pixels @ 020,012 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 024,012 */ 0, 2, 0x23, 
  /* RLE: 024 Pixels @ 026,012 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 018,013 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 019,013 */ 6, 0x01, 
  /* RLE: 001 Pixels @ 025,013 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 026,013 */ 6, 0x00, 
  /* RLE: 020 Pixels @ 000,014 */ 20, 0x01, 
  /* RLE: 004 Pixels @ 020,014 */ 4, 0x00, 
  /* RLE: 028 Pixels @ 024,014 */ 28, 0x01, 
  /* RLE: 004 Pixels @ 020,015 */ 4, 0x00, 
  /* RLE: 028 Pixels @ 024,015 */ 28, 0x01, 
  /* RLE: 004 Pixels @ 020,016 */ 4, 0x00, 
  /* RLE: 028 Pixels @ 024,016 */ 28, 0x01, 
  /* RLE: 004 Pixels @ 020,017 */ 4, 0x00, 
  /* RLE: 008 Pixels @ 024,017 */ 8, 0x01, 
  /* RLE: 018 Pixels @ 000,018 */ 18, 0x00, 
  /* RLE: 001 Pixels @ 018,018 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 019,018 */ 6, 0x01, 
  /* RLE: 001 Pixels @ 025,018 */ 1, 0x02, 
  /* RLE: 024 Pixels @ 026,018 */ 24, 0x00, 
  /* ABS: 002 Pixels @ 018,019 */ 0, 2, 0x32, 
  /* RLE: 004 Pixels @ 020,019 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 024,019 */ 0, 2, 0x23, 
  /* RLE: 076 Pixels @ 026,019 */ 76, 0x00, 
  /* ABS: 002 Pixels @ 006,022 */ 0, 2, 0x32, 
  /* RLE: 004 Pixels @ 008,022 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 012,022 */ 0, 2, 0x23, 
  /* RLE: 024 Pixels @ 014,022 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 006,023 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 007,023 */ 6, 0x01, 
  /* RLE: 001 Pixels @ 013,023 */ 1, 0x02, 
  /* RLE: 018 Pixels @ 014,023 */ 18, 0x00, 
  /* RLE: 008 Pixels @ 000,024 */ 8, 0x01, 
  /* RLE: 004 Pixels @ 008,024 */ 4, 0x00, 
  /* RLE: 028 Pixels @ 012,024 */ 28, 0x01, 
  /* RLE: 004 Pixels @ 008,025 */ 4, 0x00, 
  /* RLE: 028 Pixels @ 012,025 */ 28, 0x01, 
  /* RLE: 004 Pixels @ 008,026 */ 4, 0x00, 
  /* RLE: 028 Pixels @ 012,026 */ 28, 0x01, 
  /* RLE: 004 Pixels @ 008,027 */ 4, 0x00, 
  /* RLE: 020 Pixels @ 012,027 */ 20, 0x01, 
  /* RLE: 006 Pixels @ 000,028 */ 6, 0x00, 
  /* RLE: 001 Pixels @ 006,028 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 007,028 */ 6, 0x01, 
  /* RLE: 001 Pixels @ 013,028 */ 1, 0x02, 
  /* RLE: 024 Pixels @ 014,028 */ 24, 0x00, 
  /* ABS: 002 Pixels @ 006,029 */ 0, 2, 0x32, 
  /* RLE: 004 Pixels @ 008,029 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 012,029 */ 0, 2, 0x23, 
  /* RLE: 082 Pixels @ 014,029 */ 82, 0x00, 
  0
};  // 170 bytes for 1024 pixels

GUI_CONST_STORAGE GUI_BITMAP bmSetup_simple_32 = {
  32, // xSize
  32, // ySize
  16, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _acSetup_simple_32,  // Pointer to picture data (indices)
  &_PalSetup_simple_32,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
