/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Speedometer_32                                        *
* Dimensions:  32 * 32                                               *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmSpeedometer_32;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsSpeedometer_32[] = {
  0xFFFFFF, 0x555555, 0xAAAAAA, 0x000000
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalSpeedometer_32 = {
  4,  // Number of entries
  1,  // Has transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acSpeedometer_32[] = {
  /* RLE: 171 Pixels @ 000,000 */ 171, 0x00, 
  /* ABS: 010 Pixels @ 011,005 */ 0, 10, 0x21, 0x32, 0x00, 0x33, 0x12, 
  /* RLE: 019 Pixels @ 021,005 */ 19, 0x00, 
  /* ABS: 002 Pixels @ 008,006 */ 0, 2, 0x21, 
  /* RLE: 004 Pixels @ 010,006 */ 4, 0x03, 
  /* ABS: 003 Pixels @ 014,006 */ 0, 3, 0x20, 0x00, 
  /* RLE: 006 Pixels @ 017,006 */ 6, 0x03, 
  /* RLE: 017 Pixels @ 023,006 */ 17, 0x00, 
  /* RLE: 001 Pixels @ 008,007 */ 1, 0x02, 
  /* RLE: 005 Pixels @ 009,007 */ 5, 0x03, 
  /* ABS: 003 Pixels @ 014,007 */ 0, 3, 0x10, 0x00, 
  /* RLE: 005 Pixels @ 017,007 */ 5, 0x03, 
  /* RLE: 001 Pixels @ 022,007 */ 1, 0x01, 
  /* RLE: 014 Pixels @ 023,007 */ 14, 0x00, 
  /* ABS: 004 Pixels @ 005,008 */ 0, 4, 0x20, 0x00, 
  /* RLE: 005 Pixels @ 009,008 */ 5, 0x03, 
  /* ABS: 003 Pixels @ 014,008 */ 0, 3, 0x10, 0x20, 
  /* RLE: 005 Pixels @ 017,008 */ 5, 0x03, 
  /* ABS: 005 Pixels @ 022,008 */ 0, 5, 0x20, 0x02, 0x20, 
  /* RLE: 009 Pixels @ 027,008 */ 9, 0x00, 
  /* ABS: 006 Pixels @ 004,009 */ 0, 6, 0x23, 0x10, 0x02, 
  /* RLE: 004 Pixels @ 010,009 */ 4, 0x03, 
  /* ABS: 003 Pixels @ 014,009 */ 0, 3, 0x10, 0x20, 
  /* RLE: 005 Pixels @ 017,009 */ 5, 0x03, 
  /* ABS: 005 Pixels @ 022,009 */ 0, 5, 0x00, 0x23, 0x30, 
  /* RLE: 009 Pixels @ 027,009 */ 9, 0x00, 
  /* RLE: 003 Pixels @ 004,010 */ 3, 0x03, 
  /* ABS: 017 Pixels @ 007,010 */ 0, 17, 0x10, 0x01, 0x33, 0x12, 0x00, 0x21, 0x33, 0x20, 0x20, 
  /* RLE: 004 Pixels @ 024,010 */ 4, 0x03, 
  /* RLE: 007 Pixels @ 028,010 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 003,011 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 004,011 */ 4, 0x03, 
  /* ABS: 004 Pixels @ 008,011 */ 0, 4, 0x20, 0x22, 
  /* RLE: 011 Pixels @ 012,011 */ 11, 0x00, 
  /* RLE: 005 Pixels @ 023,011 */ 5, 0x03, 
  /* RLE: 001 Pixels @ 028,011 */ 1, 0x01, 
  /* RLE: 005 Pixels @ 029,011 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 002,012 */ 1, 0x01, 
  /* RLE: 006 Pixels @ 003,012 */ 6, 0x03, 
  /* RLE: 013 Pixels @ 009,012 */ 13, 0x00, 
  /* RLE: 001 Pixels @ 022,012 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 023,012 */ 6, 0x03, 
  /* RLE: 001 Pixels @ 029,012 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 030,012 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 002,013 */ 6, 0x03, 
  /* RLE: 001 Pixels @ 008,013 */ 1, 0x02, 
  /* RLE: 014 Pixels @ 009,013 */ 14, 0x00, 
  /* RLE: 001 Pixels @ 023,013 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 024,013 */ 4, 0x03, 
  /* RLE: 001 Pixels @ 028,013 */ 1, 0x01, 
  /* RLE: 006 Pixels @ 029,013 */ 6, 0x00, 
  /* ABS: 005 Pixels @ 003,014 */ 0, 5, 0x23, 0x33, 0x10, 
  /* RLE: 016 Pixels @ 008,014 */ 16, 0x00, 
  /* ABS: 004 Pixels @ 024,014 */ 0, 4, 0x13, 0x32, 
  /* RLE: 009 Pixels @ 028,014 */ 9, 0x00, 
  /* ABS: 002 Pixels @ 005,015 */ 0, 2, 0x11, 
  /* RLE: 018 Pixels @ 007,015 */ 18, 0x00, 
  /* RLE: 001 Pixels @ 025,015 */ 1, 0x02, 
  /* RLE: 004 Pixels @ 026,015 */ 4, 0x00, 
  /* ABS: 005 Pixels @ 030,015 */ 0, 5, 0x20, 0x21, 0x20, 
  /* RLE: 006 Pixels @ 003,016 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 009,016 */ 0, 2, 0x12, 
  /* RLE: 016 Pixels @ 011,016 */ 16, 0x00, 
  /* ABS: 017 Pixels @ 027,016 */ 0, 17, 0x21, 0x33, 0x21, 0x33, 0x31, 0x20, 0x00, 0x13, 0x10, 
  /* RLE: 014 Pixels @ 012,017 */ 14, 0x00, 
  /* RLE: 001 Pixels @ 026,017 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 027,017 */ 4, 0x03, 
  /* ABS: 002 Pixels @ 031,017 */ 0, 2, 0x11, 
  /* RLE: 004 Pixels @ 001,018 */ 4, 0x03, 
  /* RLE: 001 Pixels @ 005,018 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 006,018 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 010,018 */ 3, 0x03, 
  /* RLE: 001 Pixels @ 013,018 */ 1, 0x02, 
  /* RLE: 012 Pixels @ 014,018 */ 12, 0x00, 
  /* RLE: 001 Pixels @ 026,018 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 027,018 */ 4, 0x03, 
  /* RLE: 001 Pixels @ 031,018 */ 1, 0x01, 
  /* RLE: 005 Pixels @ 000,019 */ 5, 0x03, 
  /* RLE: 001 Pixels @ 005,019 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 006,019 */ 4, 0x00, 
  /* ABS: 006 Pixels @ 010,019 */ 0, 6, 0x13, 0x33, 0x12, 
  /* RLE: 010 Pixels @ 016,019 */ 10, 0x00, 
  /* RLE: 001 Pixels @ 026,019 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 027,019 */ 4, 0x03, 
  /* RLE: 001 Pixels @ 031,019 */ 1, 0x01, 
  /* RLE: 005 Pixels @ 000,020 */ 5, 0x03, 
  /* RLE: 001 Pixels @ 005,020 */ 1, 0x02, 
  /* RLE: 005 Pixels @ 006,020 */ 5, 0x00, 
  /* RLE: 006 Pixels @ 011,020 */ 6, 0x03, 
  /* RLE: 001 Pixels @ 017,020 */ 1, 0x01, 
  /* RLE: 008 Pixels @ 018,020 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 026,020 */ 1, 0x02, 
  /* RLE: 005 Pixels @ 027,020 */ 5, 0x03, 
  /* RLE: 005 Pixels @ 000,021 */ 5, 0x01, 
  /* RLE: 001 Pixels @ 005,021 */ 1, 0x02, 
  /* RLE: 005 Pixels @ 006,021 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 011,021 */ 1, 0x01, 
  /* RLE: 007 Pixels @ 012,021 */ 7, 0x03, 
  /* RLE: 007 Pixels @ 019,021 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 026,021 */ 1, 0x02, 
  /* RLE: 005 Pixels @ 027,021 */ 5, 0x01, 
  /* RLE: 012 Pixels @ 000,022 */ 12, 0x00, 
  /* RLE: 007 Pixels @ 012,022 */ 7, 0x03, 
  /* RLE: 001 Pixels @ 019,022 */ 1, 0x02, 
  /* RLE: 024 Pixels @ 020,022 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 012,023 */ 1, 0x01, 
  /* RLE: 006 Pixels @ 013,023 */ 6, 0x03, 
  /* RLE: 001 Pixels @ 019,023 */ 1, 0x01, 
  /* RLE: 024 Pixels @ 020,023 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 012,024 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 013,024 */ 6, 0x03, 
  /* RLE: 001 Pixels @ 019,024 */ 1, 0x02, 
  /* RLE: 025 Pixels @ 020,024 */ 25, 0x00, 
  /* RLE: 006 Pixels @ 013,025 */ 6, 0x03, 
  /* RLE: 026 Pixels @ 019,025 */ 26, 0x00, 
  /* ABS: 006 Pixels @ 013,026 */ 0, 6, 0x21, 0x33, 0x12, 
  /* RLE: 173 Pixels @ 019,026 */ 173, 0x00, 
  0
};  // 296 bytes for 1024 pixels

GUI_CONST_STORAGE GUI_BITMAP bmSpeedometer_32 = {
  32, // xSize
  32, // ySize
  16, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _acSpeedometer_32,  // Pointer to picture data (indices)
  &_PalSpeedometer_32,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
