/*
 * 3GPP_TS27.c
 *
 *  Created on: Nov 26, 2018
 *      Author: HP
 */

#include <Api/3GPP_TS2707.h>

const CommandType_TypeDef Accumulated_Call_Meter_Reset_or_Query = //
		{ "CACM", 0, extended };
const CommandType_TypeDef Accumulated_Call_Meter_Maximum_Set_or_Query = //
		{ "CAMM", 0, extended };
const CommandType_TypeDef Advice_of_Charge = //
		{ "CAOC", 0, extended };
const CommandType_TypeDef Select_Bearer_Service_Type = //
		{ "CBST", 0, extended };
const CommandType_TypeDef Call_Forwarding_Number_and_Conditions_Control = //
		{ "CCFC", 0, extended };
const CommandType_TypeDef Call_Waiting_Control = //
		{ "CCWA", 15000, extended };
const CommandType_TypeDef Extended_Error_Report = //
		{ "CEER", 0, extended };
const CommandType_TypeDef Request_Manufacturer_Identification = //
		{ "CGMI", 20000, extended };
const CommandType_TypeDef Request_Model_Identification = //
		{ "CGMM", 0, extended };
const CommandType_TypeDef Request_TA_Revision_Identification_Software_Release = //
		{ "CGMR", 0, extended };
const CommandType_TypeDef Request_Product_Serial_Number_Identification = //
		{ "CGSN", 0, extended };
const CommandType_TypeDef Select_TE_Character_Set = //
		{ "CSCS", 0, extended };
const CommandType_TypeDef Select_Type_Address = //
		{ "CSTA", 0, extended };
const CommandType_TypeDef Call_Hold_and_Multiparty = //
		{ "CHLD", 20000, extended };
const CommandType_TypeDef Request_International_Mobile_Subscriber_Identity = //
		{ "CIMI", 20000, extended };
const CommandType_TypeDef List_Current_Calls_ME = //
		{ "CLCC", 0, extended };
const CommandType_TypeDef Facility_Lock = //
		{ "CLCK", 0, extended };
const CommandType_TypeDef Calling_Line_Identification_Presentation = //
		{ "CLIP", 15000, extended };
const CommandType_TypeDef Calling_Line_Identification_Restriction = //
		{ "CLIR", 15000, extended };
const CommandType_TypeDef Report_Mobile_Equipment_Error = //
		{ "CMEE", 0, extended };
const CommandType_TypeDef Connected_Line_Identification_Presentation = //
		{ "COLP", 0, extended };
const CommandType_TypeDef Operator_Selection = //
		{ "COPS", 12000, extended };
const CommandType_TypeDef Phone_Activity_Status = //
		{ "CPAS", 0, extended };
const CommandType_TypeDef Find_Phonebook_Entries = //
		{ "CPBF", 0, extended };
const CommandType_TypeDef Read_Current_Phonebook_Entries = //
		{ "CPBR", 0, extended };
const CommandType_TypeDef Select_Phonebook_Memory_Storage = //
		{ "CPBS", 3000, extended };
const CommandType_TypeDef Write_Phonebook_Entry = //
		{ "CPBW", 3000, extended };
const CommandType_TypeDef SET_DCDEnter_PIN_FUNCTION_MODE = //
		{ "CPIN", 0, extended };
const CommandType_TypeDef Change_Password = //
		{ "CPWD", 5000, extended };
const CommandType_TypeDef Service_Reporting_Control = //
		{ "CR", 0, extended };
const CommandType_TypeDef Set_Cellular_Result_Codes_Incoming_Call_Indication = //
		{ "CRC", 0, extended };
const CommandType_TypeDef Network_Registration = //
		{ "CREG", 0, extended };
const CommandType_TypeDef Select_Radio_Link_Protocol_Parameters = //
		{ "CRLP", 0, extended };
const CommandType_TypeDef Restricted_SIM_Access = //
		{ "CRSM", 0, extended };
const CommandType_TypeDef Signal_Quality_Report = //
		{ "CSQ", 0, extended };
const CommandType_TypeDef Tone_Duration = //
		{ "VTD", 0, extended };
const CommandType_TypeDef DTMF_Tone_Generation = //
		{ "VTS", 0, extended };
const CommandType_TypeDef Multiplexer_Control = //
		{ "CMUX", 0, extended };
const CommandType_TypeDef Subscriber_Number = //
		{ "CNUM", 0, extended };
const CommandType_TypeDef Preferred_Operator_List = //
		{ "CPOL", 0, extended };
const CommandType_TypeDef Read_Operator_Names = //
		{ "COPN", 0, extended };
const CommandType_TypeDef Set_Phone_Functionality = //
		{ "CFUN", 10000, extended };
const CommandType_TypeDef Clock = //
		{ "CCLK", 0, extended };
const CommandType_TypeDef Generic_SIM_Access = //
		{ "CSIM", 0, extended };
const CommandType_TypeDef Alert_Sound_Mode = //
		{ "CALM", 0, extended };
const CommandType_TypeDef Alert_Sound_Select = //
		{ "CALS", 0, extended };
const CommandType_TypeDef Ringer_Sound_Level = //
		{ "CRSL", 0, extended };
const CommandType_TypeDef Loud_Speaker_Volume_Level = //
		{ "CLVL", 0, extended };
const CommandType_TypeDef Mute_Control = //
		{ "CMUT", 0, extended };
const CommandType_TypeDef Price_Per_Unit_and_Currency_Table = //
		{ "CPUC", 5000, extended };
const CommandType_TypeDef Call_Meter_Maximum_Even = //
		{ "CCWE", 0, extended };
const CommandType_TypeDef Battery_Charge = //
		{ "CBC", 0, extended };
const CommandType_TypeDef Unstructured_Supplementary_Service_Data = //
		{ "CUSD", 0, extended };
const CommandType_TypeDef Supplementary_Services_Notification = //
		{ "CSSN", 0, extended };

