/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: messagereply                                          *
* Dimensions:  16 * 16                                               *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmmessagereply;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsmessagereply[] = {
  0xFEFEFE, 0x606060, 0xA2A2A2, 0x050505
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palmessagereply = {
  4,  // Number of entries
  1,  // Has transparency
  &_Colorsmessagereply[0]
};

static GUI_CONST_STORAGE unsigned char _acmessagereply[] = {
  /* RLE: 032 Pixels @ 000,000 */ 32, 0x00, 
  /* RLE: 001 Pixels @ 000,002 */ 1, 0x02, 
  /* RLE: 011 Pixels @ 001,002 */ 11, 0x03, 
  /* RLE: 004 Pixels @ 012,002 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 000,003 */ 0, 2, 0x21, 
  /* RLE: 009 Pixels @ 002,003 */ 9, 0x03, 
  /* ABS: 008 Pixels @ 011,003 */ 0, 8, 0x22, 0x00, 0x03, 0x12, 
  /* RLE: 007 Pixels @ 003,004 */ 7, 0x03, 
  /* ABS: 010 Pixels @ 010,004 */ 0, 10, 0x23, 0x10, 0x00, 0x33, 0x12, 
  /* RLE: 004 Pixels @ 004,005 */ 4, 0x03, 
  /* ABS: 008 Pixels @ 008,005 */ 0, 8, 0x12, 0x33, 0x10, 0x00, 
  /* RLE: 004 Pixels @ 000,006 */ 4, 0x03, 
  /* ABS: 012 Pixels @ 004,006 */ 0, 12, 0x21, 0x31, 0x23, 0x33, 0x10, 0x00, 
  /* RLE: 005 Pixels @ 000,007 */ 5, 0x03, 
  /* ABS: 003 Pixels @ 005,007 */ 0, 3, 0x22, 0x10, 
  /* RLE: 004 Pixels @ 008,007 */ 4, 0x03, 
  /* ABS: 004 Pixels @ 012,007 */ 0, 4, 0x10, 0x00, 
  /* RLE: 010 Pixels @ 000,008 */ 10, 0x03, 
  /* RLE: 003 Pixels @ 010,008 */ 3, 0x02, 
  /* RLE: 003 Pixels @ 013,008 */ 3, 0x00, 
  /* RLE: 009 Pixels @ 000,009 */ 9, 0x03, 
  /* ABS: 007 Pixels @ 009,009 */ 0, 7, 0x21, 0x13, 0x20, 0x00, 
  /* RLE: 008 Pixels @ 000,010 */ 8, 0x03, 
  /* ABS: 009 Pixels @ 008,010 */ 0, 9, 0x21, 0x13, 0x33, 0x10, 0x00, 
  /* RLE: 009 Pixels @ 001,011 */ 9, 0x02, 
  /* RLE: 005 Pixels @ 010,011 */ 5, 0x03, 
  /* RLE: 001 Pixels @ 015,011 */ 1, 0x01, 
  /* RLE: 009 Pixels @ 000,012 */ 9, 0x00, 
  /* ABS: 002 Pixels @ 009,012 */ 0, 2, 0x22, 
  /* RLE: 005 Pixels @ 011,012 */ 5, 0x03, 
  /* RLE: 010 Pixels @ 000,013 */ 10, 0x00, 
  /* ABS: 006 Pixels @ 010,013 */ 0, 6, 0x22, 0x32, 0x01, 
  /* RLE: 032 Pixels @ 000,014 */ 32, 0x00, 
  0
};  // 103 bytes for 256 pixels

GUI_CONST_STORAGE GUI_BITMAP bmmessagereply = {
  16, // xSize
  16, // ySize
  8, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _acmessagereply,  // Pointer to picture data (indices)
  &_Palmessagereply,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
