/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: messageforward                                        *
* Dimensions:  16 * 16                                               *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmmessageforward;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsmessageforward[] = {
  0xFDFDFD, 0x060606, 0xA1A1A1, 0x5A5A5A
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palmessageforward = {
  4,  // Number of entries
  1,  // Has transparency
  &_Colorsmessageforward[0]
};

static GUI_CONST_STORAGE unsigned char _acmessageforward[] = {
  /* RLE: 032 Pixels @ 000,000 */ 32, 0x00, 
  /* RLE: 001 Pixels @ 000,002 */ 1, 0x02, 
  /* RLE: 011 Pixels @ 001,002 */ 11, 0x01, 
  /* RLE: 004 Pixels @ 012,002 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 000,003 */ 0, 2, 0x23, 
  /* RLE: 009 Pixels @ 002,003 */ 9, 0x01, 
  /* ABS: 008 Pixels @ 011,003 */ 0, 8, 0x22, 0x00, 0x01, 0x32, 
  /* RLE: 007 Pixels @ 003,004 */ 7, 0x01, 
  /* ABS: 010 Pixels @ 010,004 */ 0, 10, 0x21, 0x30, 0x00, 0x11, 0x32, 
  /* RLE: 004 Pixels @ 004,005 */ 4, 0x01, 
  /* ABS: 008 Pixels @ 008,005 */ 0, 8, 0x32, 0x11, 0x30, 0x00, 
  /* RLE: 004 Pixels @ 000,006 */ 4, 0x01, 
  /* ABS: 012 Pixels @ 004,006 */ 0, 12, 0x23, 0x13, 0x21, 0x11, 0x20, 0x00, 
  /* RLE: 005 Pixels @ 000,007 */ 5, 0x01, 
  /* ABS: 011 Pixels @ 005,007 */ 0, 11, 0x22, 0x31, 0x11, 0x22, 0x00, 0x00, 
  /* RLE: 008 Pixels @ 000,008 */ 8, 0x01, 
  /* ABS: 008 Pixels @ 008,008 */ 0, 8, 0x33, 0x23, 0x13, 0x00, 
  /* RLE: 007 Pixels @ 000,009 */ 7, 0x01, 
  /* ABS: 004 Pixels @ 007,009 */ 0, 4, 0x32, 0x33, 
  /* RLE: 004 Pixels @ 011,009 */ 4, 0x01, 
  /* RLE: 001 Pixels @ 015,009 */ 1, 0x00, 
  /* RLE: 007 Pixels @ 000,010 */ 7, 0x01, 
  /* RLE: 001 Pixels @ 007,010 */ 1, 0x02, 
  /* RLE: 008 Pixels @ 008,010 */ 8, 0x01, 
  /* RLE: 001 Pixels @ 000,011 */ 1, 0x00, 
  /* RLE: 006 Pixels @ 001,011 */ 6, 0x02, 
  /* RLE: 001 Pixels @ 007,011 */ 1, 0x00, 
  /* RLE: 007 Pixels @ 008,011 */ 7, 0x01, 
  /* RLE: 001 Pixels @ 015,011 */ 1, 0x02, 
  /* RLE: 011 Pixels @ 000,012 */ 11, 0x00, 
  /* ABS: 004 Pixels @ 011,012 */ 0, 4, 0x31, 0x12, 
  /* RLE: 012 Pixels @ 015,012 */ 12, 0x00, 
  /* ABS: 002 Pixels @ 011,013 */ 0, 2, 0x31, 
  /* RLE: 035 Pixels @ 013,013 */ 35, 0x00, 
  0
};  // 103 bytes for 256 pixels

GUI_CONST_STORAGE GUI_BITMAP bmmessageforward = {
  16, // xSize
  16, // ySize
  8, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _acmessageforward,  // Pointer to picture data (indices)
  &_Palmessageforward,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
