/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: delete                                                *
* Dimensions:  16 * 16                                               *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif



/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsdelete[] = {
  0xF5F5F5, 0x626061, 0xA7A6A7, 0x0E0D0D
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Paldelete = {
  4,  // Number of entries
  1,  // Has transparency
  &_Colorsdelete[0]
};

static GUI_CONST_STORAGE unsigned char _acdelete[] = {
  /* RLE: 004 Pixels @ 000,000 */ 4, 0x00,
  /* ABS: 002 Pixels @ 004,000 */ 0, 2, 0x21,
  /* RLE: 004 Pixels @ 006,000 */ 4, 0x03,
  /* ABS: 002 Pixels @ 010,000 */ 0, 2, 0x12,
  /* RLE: 007 Pixels @ 012,000 */ 7, 0x00,
  /* RLE: 001 Pixels @ 003,001 */ 1, 0x01,
  /* RLE: 008 Pixels @ 004,001 */ 8, 0x03,
  /* RLE: 001 Pixels @ 012,001 */ 1, 0x01,
  /* RLE: 005 Pixels @ 013,001 */ 5, 0x00,
  /* ABS: 004 Pixels @ 002,002 */ 0, 4, 0x13, 0x32,
  /* RLE: 004 Pixels @ 006,002 */ 4, 0x00,
  /* ABS: 010 Pixels @ 010,002 */ 0, 10, 0x23, 0x31, 0x00, 0x01, 0x33,
  /* RLE: 008 Pixels @ 004,003 */ 8, 0x00,
  /* ABS: 041 Pixels @ 012,003 */ 0, 41, 0x33, 0x10, 0x23, 0x30, 0x00, 0x20, 0x02, 0x00, 0x03, 0x32, 0x13, 0x20, 0x03, 0x32, 0x23, 0x30, 0x02, 0x31, 0x33, 0x00, 0x20,
  /* RLE: 006 Pixels @ 005,006 */ 6, 0x03,
  /* ABS: 003 Pixels @ 011,006 */ 0, 3, 0x20, 0x00,
  /* RLE: 004 Pixels @ 014,006 */ 4, 0x03,
  /* RLE: 003 Pixels @ 002,007 */ 3, 0x00,
  /* RLE: 001 Pixels @ 005,007 */ 1, 0x02,
  /* RLE: 004 Pixels @ 006,007 */ 4, 0x03,
  /* ABS: 004 Pixels @ 010,007 */ 0, 4, 0x20, 0x00,
  /* RLE: 004 Pixels @ 014,007 */ 4, 0x03,
  /* RLE: 003 Pixels @ 002,008 */ 3, 0x00,
  /* RLE: 001 Pixels @ 005,008 */ 1, 0x02,
  /* RLE: 004 Pixels @ 006,008 */ 4, 0x03,
  /* ABS: 004 Pixels @ 010,008 */ 0, 4, 0x20, 0x00,
  /* RLE: 004 Pixels @ 014,008 */ 4, 0x03,
  /* ABS: 003 Pixels @ 002,009 */ 0, 3, 0x00, 0x20,
  /* RLE: 006 Pixels @ 005,009 */ 6, 0x03,
  /* ABS: 041 Pixels @ 011,009 */ 0, 41, 0x20, 0x03, 0x31, 0x32, 0x00, 0x33, 0x22, 0x33, 0x00, 0x23, 0x12, 0x33, 0x00, 0x02, 0x00, 0x20, 0x00, 0x33, 0x20, 0x13, 0x30,
  /* RLE: 008 Pixels @ 004,012 */ 8, 0x00,
  /* ABS: 010 Pixels @ 012,012 */ 0, 10, 0x33, 0x10, 0x00, 0x13, 0x32,
  /* RLE: 004 Pixels @ 006,013 */ 4, 0x00,
  /* ABS: 004 Pixels @ 010,013 */ 0, 4, 0x23, 0x31,
  /* RLE: 005 Pixels @ 014,013 */ 5, 0x00,
  /* RLE: 001 Pixels @ 003,014 */ 1, 0x01,
  /* RLE: 008 Pixels @ 004,014 */ 8, 0x03,
  /* RLE: 001 Pixels @ 012,014 */ 1, 0x01,
  /* RLE: 007 Pixels @ 013,014 */ 7, 0x00,
  /* ABS: 002 Pixels @ 004,015 */ 0, 2, 0x21,
  /* RLE: 004 Pixels @ 006,015 */ 4, 0x03,
  /* ABS: 002 Pixels @ 010,015 */ 0, 2, 0x12,
  /* RLE: 004 Pixels @ 012,015 */ 4, 0x00,
  0
};  // 154 bytes for 256 pixels

GUI_CONST_STORAGE GUI_BITMAP bmdelete = {
  16, // xSize
  16, // ySize
  8, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _acdelete,  // Pointer to picture data (indices)
  &_Paldelete,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
