/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: pencil                                                *
* Dimensions:  16 * 16                                               *
* NumColors:   4                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif



/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorspencil[] = {
  0xF9F9F9, 0x686868, 0xBCBCBC, 0x101010
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palpencil = {
  4,  // Number of entries
  1,  // Has transparency
  &_Colorspencil[0]
};

static GUI_CONST_STORAGE unsigned char _acpencil[] = {
  /* RLE: 012 Pixels @ 000,000 */ 12, 0x00,
  /* ABS: 002 Pixels @ 012,000 */ 0, 2, 0x12,
  /* RLE: 013 Pixels @ 014,000 */ 13, 0x00,
  /* RLE: 003 Pixels @ 011,001 */ 3, 0x03,
  /* RLE: 001 Pixels @ 014,001 */ 1, 0x02,
  /* RLE: 011 Pixels @ 015,001 */ 11, 0x00,
  /* RLE: 001 Pixels @ 010,002 */ 1, 0x01,
  /* RLE: 004 Pixels @ 011,002 */ 4, 0x03,
  /* RLE: 001 Pixels @ 015,002 */ 1, 0x02,
  /* RLE: 009 Pixels @ 000,003 */ 9, 0x00,
  /* ABS: 002 Pixels @ 009,003 */ 0, 2, 0x10,
  /* RLE: 004 Pixels @ 011,003 */ 4, 0x03,
  /* RLE: 001 Pixels @ 015,003 */ 1, 0x01,
  /* RLE: 008 Pixels @ 000,004 */ 8, 0x00,
  /* ABS: 007 Pixels @ 008,004 */ 0, 7, 0x33, 0x10, 0x33, 0x30,
  /* RLE: 008 Pixels @ 015,004 */ 8, 0x00,
  /* RLE: 004 Pixels @ 007,005 */ 4, 0x03,
  /* ABS: 003 Pixels @ 011,005 */ 0, 3, 0x10, 0x10,
  /* RLE: 008 Pixels @ 014,005 */ 8, 0x00,
  /* RLE: 006 Pixels @ 006,006 */ 6, 0x03,
  /* RLE: 001 Pixels @ 012,006 */ 1, 0x01,
  /* RLE: 008 Pixels @ 013,006 */ 8, 0x00,
  /* RLE: 007 Pixels @ 005,007 */ 7, 0x03,
  /* RLE: 008 Pixels @ 012,007 */ 8, 0x00,
  /* RLE: 007 Pixels @ 004,008 */ 7, 0x03,
  /* RLE: 008 Pixels @ 011,008 */ 8, 0x00,
  /* RLE: 007 Pixels @ 003,009 */ 7, 0x03,
  /* RLE: 008 Pixels @ 010,009 */ 8, 0x00,
  /* RLE: 007 Pixels @ 002,010 */ 7, 0x03,
  /* RLE: 009 Pixels @ 009,010 */ 9, 0x00,
  /* RLE: 001 Pixels @ 002,011 */ 1, 0x01,
  /* RLE: 005 Pixels @ 003,011 */ 5, 0x03,
  /* RLE: 009 Pixels @ 008,011 */ 9, 0x00,
  /* ABS: 006 Pixels @ 001,012 */ 0, 6, 0x30, 0x13, 0x33,
  /* RLE: 009 Pixels @ 007,012 */ 9, 0x00,
  /* ABS: 006 Pixels @ 000,013 */ 0, 6, 0x23, 0x30, 0x13,
  /* RLE: 010 Pixels @ 006,013 */ 10, 0x00,
  /* ABS: 004 Pixels @ 000,014 */ 0, 4, 0x13, 0x33,
  /* RLE: 012 Pixels @ 004,014 */ 12, 0x00,
  /* ABS: 003 Pixels @ 000,015 */ 0, 3, 0x11, 0x20,
  /* RLE: 013 Pixels @ 003,015 */ 13, 0x00,
  0
};  // 100 bytes for 256 pixels

GUI_CONST_STORAGE GUI_BITMAP bmpencil = {
  16, // xSize
  16, // ySize
  8, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _acpencil,  // Pointer to picture data (indices)
  &_Palpencil,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
