/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "WM.h"
#include "DIALOG.h"

#include "ViewContainer/ViewNavigator.h"
#include "MemoryDataContext.h"

#include "Contact.h"

#include "ViewContainer/ListView.h"
#include "ViewContainer/OptionListView.h"
#include "ViewContainer/EditView.h"

#include "Api/V25TER.h"








/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_02     (GUI_ID_USER + 0x10)
#define ID_LISTBOX_0     (GUI_ID_USER + 0x11)

extern GUI_CONST_STORAGE GUI_BITMAP bmphonecall;
extern GUI_CONST_STORAGE GUI_BITMAP bmpencil;
extern GUI_CONST_STORAGE GUI_BITMAP bmloupe;
extern GUI_CONST_STORAGE GUI_BITMAP bmdelete;



void InitContactView(void);
static void CallFunctionCallback(void);
static void EditFunctionCallback(void);
static void ViewInfoFunctionCallBcak(void);
static void DeleteFunctionCallback(void);
static void AddFunctionCallback(void);

static void EditContactProgress(void * arg, GUI_HWIN currentWidget);

extern ListApiHandlers_typedef ContactListApiHandlers;



extern View_Typedef ListView;
extern View_Typedef EditView;
extern View_Typedef OptionListView;



static void ContactListSelectCallback(void *);
const CustomFunction_Typedef AddFunction = { NULL, "Add New...",
		AddFunctionCallback };
const CustomFunction_Typedef * ContactListFunctionList[2] =
		{ &AddFunction, NULL };
ListView_Parameters_Typedef ListView_Parameters = { //
		ContactListFunctionList, // custom function list
				&ContactListApiHandlers,  // list api handler
				ContactListSelectCallback, // list select callback
				0, // not document
				0 // not document
		};




static void ContactOptionSelectCallback(void *);
const CustomFunction_Typedef CallFunction = { &bmphonecall,
		(const char*) "Call", CallFunctionCallback };
const CustomFunction_Typedef EditFunction = { &bmpencil, "Edit",
		EditFunctionCallback };
const CustomFunction_Typedef ViewInfoFunction = { &bmloupe, "View",
		ViewInfoFunctionCallBcak };
const CustomFunction_Typedef DeleteFunction = { &bmdelete, "Delete",
		DeleteFunctionCallback };
const CustomFunction_Typedef * ContactOptionFunctionList[5] = { &CallFunction,
		&EditFunction, &ViewInfoFunction, &DeleteFunction, NULL };
typedef struct {
	CustomFunction_Typedef **customFunction;
	void (*SelectCallback)(void *);
	LISTBOX_Handle hWin;
} OptionListView_Parameters_Typedef;
OptionListView_Parameters_Typedef OptionListView_Parameters = { //
		ContactOptionFunctionList, // custom function list
				ContactOptionSelectCallback, // option select callback
				0, // not document
		};


void (*FinishCallback)(void *);
extern const FieldAttribute_Typedef ContactFieldsAttribute[CONTACT_FIELD_COUNT];
EditView_Parameters_Typedef EditView_Parameters = { //
		&ContactFieldsAttribute, //
				FinishCallback, //
				CONTACT_FIELD_COUNT, //
				0, //
				0, //
				0, //
		};


typedef enum {
	EditContactState_Name,
	EditContactState_LastName,
	EditContactState_CallNumber,
	EditContactState_Finished,
} EditContactState_Typedef;

void InitContactView() {

	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &ListView,
			&ListView_Parameters);
}

void EditFunctionCallback() {
	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &ListEditView);
}

void ViewInfoFunctionCallBcak() {
	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &ListInfoView);
}

void DeleteFunctionCallback() {
	DefaultListView->ApiHandlers->Remove();
	ViewNavigator_GoBackView(&DefaultViewNavigator);
}
void AddFunctionCallback() {

}
static void CallFunctionCallback(void) {
	Contact_Typedef *contact = ContactListApiHandlers.GetSelectedItem();
	char num[20];
	strcpy(num, contact->CallNumber);
	strcat(num, ";");
	GSM_CALL_TO_DIAL_A_NUMBER(num);
}

void ContactListSelectCallback(void *) {

}
void FinishCallback(void *) {

}
// USER END

/*************************** End of file ****************************/
