/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: calling0                                              *
* Dimensions:  64 * 64                                               *
* NumColors:   16                                                    *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif



/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorscalling0[] = {
  0xFEFEFE, 0x0F9943, 0x229C4F, 0x05B048,
  0x2DA158, 0x3DA865, 0x4EB072, 0x06C251,
  0x5EB780, 0x62B883, 0x77C294, 0x97D0AC,
  0xB6DEC5, 0xCBE8D6, 0xD8EEE0, 0x049038
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palcalling0 = {
  16,  // Number of entries
  1,   // Has transparency
  &_Colorscalling0[0]
};

static GUI_CONST_STORAGE unsigned char _accalling0[] = {
  /* RLE: 392 Pixels @ 000,000 */ 254, 0x00, 138, 0x00,
  /* ABS: 007 Pixels @ 008,006 */ 0, 7, 0xE8, 0x1F, 0x19, 0xE0,
  /* RLE: 056 Pixels @ 015,006 */ 56, 0x00,
  /* ABS: 002 Pixels @ 007,007 */ 0, 2, 0xC1,
  /* RLE: 005 Pixels @ 009,007 */ 5, 0x0F,
  /* ABS: 002 Pixels @ 014,007 */ 0, 2, 0x1C,
  /* RLE: 054 Pixels @ 016,007 */ 54, 0x00,
  /* ABS: 011 Pixels @ 006,008 */ 0, 11, 0xCF, 0xF1, 0x37, 0x3F, 0xFF, 0xB0,
  /* RLE: 052 Pixels @ 017,008 */ 52, 0x00,
  /* ABS: 004 Pixels @ 005,009 */ 0, 4, 0xCF, 0xF1,
  /* RLE: 005 Pixels @ 009,009 */ 5, 0x07,
  /* ABS: 004 Pixels @ 014,009 */ 0, 4, 0x3F, 0xFB,
  /* RLE: 050 Pixels @ 018,009 */ 50, 0x00,
  /* ABS: 004 Pixels @ 004,010 */ 0, 4, 0xCF, 0xF1,
  /* RLE: 007 Pixels @ 008,010 */ 7, 0x07,
  /* ABS: 004 Pixels @ 015,010 */ 0, 4, 0x3F, 0xFC,
  /* RLE: 048 Pixels @ 019,010 */ 48, 0x00,
  /* ABS: 004 Pixels @ 003,011 */ 0, 4, 0xD1, 0xF1,
  /* RLE: 009 Pixels @ 007,011 */ 9, 0x07,
  /* ABS: 004 Pixels @ 016,011 */ 0, 4, 0x1F, 0x1E,
  /* RLE: 047 Pixels @ 020,011 */ 47, 0x00,
  /* ABS: 003 Pixels @ 003,012 */ 0, 3, 0x2F, 0x10,
  /* RLE: 011 Pixels @ 006,012 */ 11, 0x07,
  /* ABS: 003 Pixels @ 017,012 */ 0, 3, 0x1F, 0x40,
  /* RLE: 046 Pixels @ 020,012 */ 46, 0x00,
  /* ABS: 003 Pixels @ 002,013 */ 0, 3, 0x8F, 0xF0,
  /* RLE: 013 Pixels @ 005,013 */ 13, 0x07,
  /* ABS: 003 Pixels @ 018,013 */ 0, 3, 0xFF, 0x90,
  /* RLE: 044 Pixels @ 021,013 */ 44, 0x00,
  /* ABS: 004 Pixels @ 001,014 */ 0, 4, 0xCF, 0xF3,
  /* RLE: 013 Pixels @ 005,014 */ 13, 0x07,
  /* ABS: 004 Pixels @ 018,014 */ 0, 4, 0x3F, 0xFC,
  /* RLE: 043 Pixels @ 022,014 */ 43, 0x00,
  /* ABS: 003 Pixels @ 001,015 */ 0, 3, 0x5F, 0x10,
  /* RLE: 015 Pixels @ 004,015 */ 15, 0x07,
  /* ABS: 003 Pixels @ 019,015 */ 0, 3, 0x1F, 0x20,
  /* RLE: 042 Pixels @ 022,015 */ 42, 0x00,
  /* ABS: 003 Pixels @ 000,016 */ 0, 3, 0xEF, 0xF0,
  /* RLE: 017 Pixels @ 003,016 */ 17, 0x07,
  /* ABS: 003 Pixels @ 020,016 */ 0, 3, 0xFF, 0xA0,
  /* RLE: 041 Pixels @ 023,016 */ 41, 0x00,
  /* ABS: 003 Pixels @ 000,017 */ 0, 3, 0xBF, 0x10,
  /* RLE: 017 Pixels @ 003,017 */ 17, 0x07,
  /* ABS: 003 Pixels @ 020,017 */ 0, 3, 0x3F, 0x10,
  /* RLE: 041 Pixels @ 023,017 */ 41, 0x00,
  /* ABS: 003 Pixels @ 000,018 */ 0, 3, 0x6F, 0x30,
  /* RLE: 018 Pixels @ 003,018 */ 18, 0x07,
  /* ABS: 003 Pixels @ 021,018 */ 0, 3, 0xFF, 0xC0,
  /* RLE: 040 Pixels @ 024,018 */ 40, 0x00,
  /* ABS: 003 Pixels @ 000,019 */ 0, 3, 0x2F, 0x30,
  /* RLE: 018 Pixels @ 003,019 */ 18, 0x07,
  /* ABS: 003 Pixels @ 021,019 */ 0, 3, 0xFF, 0xC0,
  /* RLE: 040 Pixels @ 024,019 */ 40, 0x00,
  /* ABS: 002 Pixels @ 000,020 */ 0, 2, 0x1F,
  /* RLE: 018 Pixels @ 002,020 */ 18, 0x07,
  /* ABS: 004 Pixels @ 020,020 */ 0, 4, 0x3F, 0xFE,
  /* RLE: 040 Pixels @ 024,020 */ 40, 0x00,
  /* ABS: 002 Pixels @ 000,021 */ 0, 2, 0xFF,
  /* RLE: 010 Pixels @ 002,021 */ 10, 0x07,
  /* ABS: 002 Pixels @ 012,021 */ 0, 2, 0xF1,
  /* RLE: 005 Pixels @ 014,021 */ 5, 0x07,
  /* ABS: 004 Pixels @ 019,021 */ 0, 4, 0x3F, 0xF6,
  /* RLE: 041 Pixels @ 023,021 */ 41, 0x00,
  /* ABS: 003 Pixels @ 000,022 */ 0, 3, 0x2F, 0x30,
  /* RLE: 009 Pixels @ 003,022 */ 9, 0x07,
  /* ABS: 002 Pixels @ 012,022 */ 0, 2, 0xFF,
  /* RLE: 004 Pixels @ 014,022 */ 4, 0x07,
  /* ABS: 004 Pixels @ 018,022 */ 0, 4, 0x3F, 0xF8,
  /* RLE: 042 Pixels @ 022,022 */ 42, 0x00,
  /* ABS: 003 Pixels @ 000,023 */ 0, 3, 0x5F, 0x30,
  /* RLE: 009 Pixels @ 003,023 */ 9, 0x07,
  /* ABS: 009 Pixels @ 012,023 */ 0, 9, 0xFF, 0x77, 0x71, 0xFF, 0xA0,
  /* RLE: 043 Pixels @ 021,023 */ 43, 0x00,
  /* ABS: 003 Pixels @ 000,024 */ 0, 3, 0x9F, 0x30,
  /* RLE: 009 Pixels @ 003,024 */ 9, 0x07,
  /* ABS: 008 Pixels @ 012,024 */ 0, 8, 0x1F, 0x37, 0x3F, 0xFB,
  /* RLE: 044 Pixels @ 020,024 */ 44, 0x00,
  /* ABS: 003 Pixels @ 000,025 */ 0, 3, 0xCF, 0xF0,
  /* RLE: 009 Pixels @ 003,025 */ 9, 0x07,
  /* ABS: 007 Pixels @ 012,025 */ 0, 7, 0x3F, 0x17, 0xFF, 0xB0,
  /* RLE: 046 Pixels @ 019,025 */ 46, 0x00,
  /* ABS: 003 Pixels @ 001,026 */ 0, 3, 0x1F, 0x30,
  /* RLE: 009 Pixels @ 004,026 */ 9, 0x07,
  /* ABS: 005 Pixels @ 013,026 */ 0, 5, 0xFF, 0x1F, 0x40,
  /* RLE: 047 Pixels @ 018,026 */ 47, 0x00,
  /* ABS: 003 Pixels @ 001,027 */ 0, 3, 0x8F, 0x10,
  /* RLE: 009 Pixels @ 004,027 */ 9, 0x07,
  /* ABS: 005 Pixels @ 013,027 */ 0, 5, 0x1F, 0xFF, 0xA0,
  /* RLE: 047 Pixels @ 018,027 */ 47, 0x00,
  /* ABS: 003 Pixels @ 001,028 */ 0, 3, 0xDF, 0xF0,
  /* RLE: 010 Pixels @ 004,028 */ 10, 0x07,
  /* RLE: 003 Pixels @ 014,028 */ 3, 0x0F,
  /* RLE: 001 Pixels @ 017,028 */ 1, 0x0B,
  /* RLE: 048 Pixels @ 018,028 */ 48, 0x00,
  /* ABS: 003 Pixels @ 002,029 */ 0, 3, 0x6F, 0x10,
  /* RLE: 009 Pixels @ 005,029 */ 9, 0x07,
  /* ABS: 004 Pixels @ 014,029 */ 0, 4, 0x3F, 0xFA,
  /* RLE: 048 Pixels @ 018,029 */ 48, 0x00,
  /* ABS: 004 Pixels @ 002,030 */ 0, 4, 0xEF, 0xF3,
  /* RLE: 009 Pixels @ 006,030 */ 9, 0x07,
  /* ABS: 003 Pixels @ 015,030 */ 0, 3, 0xFF, 0x10,
  /* RLE: 049 Pixels @ 018,030 */ 49, 0x00,
  /* ABS: 003 Pixels @ 003,031 */ 0, 3, 0xAF, 0xF0,
  /* RLE: 009 Pixels @ 006,031 */ 9, 0x07,
  /* ABS: 004 Pixels @ 015,031 */ 0, 4, 0x3F, 0xF6,
  /* RLE: 049 Pixels @ 019,031 */ 49, 0x00,
  /* ABS: 003 Pixels @ 004,032 */ 0, 3, 0x4F, 0x10,
  /* RLE: 009 Pixels @ 007,032 */ 9, 0x07,
  /* ABS: 004 Pixels @ 016,032 */ 0, 4, 0x3F, 0xF8,
  /* RLE: 048 Pixels @ 020,032 */ 48, 0x00,
  /* ABS: 004 Pixels @ 004,033 */ 0, 4, 0xD1, 0xF3,
  /* RLE: 009 Pixels @ 008,033 */ 9, 0x07,
  /* ABS: 004 Pixels @ 017,033 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 048 Pixels @ 021,033 */ 48, 0x00,
  /* ABS: 004 Pixels @ 005,034 */ 0, 4, 0xBF, 0xF3,
  /* RLE: 009 Pixels @ 009,034 */ 9, 0x07,
  /* ABS: 004 Pixels @ 018,034 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 048 Pixels @ 022,034 */ 48, 0x00,
  /* ABS: 004 Pixels @ 006,035 */ 0, 4, 0xAF, 0xF3,
  /* RLE: 009 Pixels @ 010,035 */ 9, 0x07,
  /* ABS: 004 Pixels @ 019,035 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 048 Pixels @ 023,035 */ 48, 0x00,
  /* ABS: 004 Pixels @ 007,036 */ 0, 4, 0x6F, 0xF3,
  /* RLE: 009 Pixels @ 011,036 */ 9, 0x07,
  /* ABS: 004 Pixels @ 020,036 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 048 Pixels @ 024,036 */ 48, 0x00,
  /* ABS: 004 Pixels @ 008,037 */ 0, 4, 0x6F, 0xF3,
  /* RLE: 009 Pixels @ 012,037 */ 9, 0x07,
  /* ABS: 004 Pixels @ 021,037 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 048 Pixels @ 025,037 */ 48, 0x00,
  /* ABS: 004 Pixels @ 009,038 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 009 Pixels @ 013,038 */ 9, 0x07,
  /* ABS: 004 Pixels @ 022,038 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 048 Pixels @ 026,038 */ 48, 0x00,
  /* ABS: 004 Pixels @ 010,039 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 009 Pixels @ 014,039 */ 9, 0x07,
  /* ABS: 004 Pixels @ 023,039 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 048 Pixels @ 027,039 */ 48, 0x00,
  /* ABS: 004 Pixels @ 011,040 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 009 Pixels @ 015,040 */ 9, 0x07,
  /* ABS: 004 Pixels @ 024,040 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 014 Pixels @ 028,040 */ 14, 0x00,
  /* ABS: 005 Pixels @ 042,040 */ 0, 5, 0xA4, 0x48, 0xC0,
  /* RLE: 029 Pixels @ 047,040 */ 29, 0x00,
  /* ABS: 004 Pixels @ 012,041 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 009 Pixels @ 016,041 */ 9, 0x07,
  /* ABS: 004 Pixels @ 025,041 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 012 Pixels @ 029,041 */ 12, 0x00,
  /* RLE: 001 Pixels @ 041,041 */ 1, 0x05,
  /* RLE: 005 Pixels @ 042,041 */ 5, 0x0F,
  /* ABS: 002 Pixels @ 047,041 */ 0, 2, 0x5E,
  /* RLE: 028 Pixels @ 049,041 */ 28, 0x00,
  /* ABS: 004 Pixels @ 013,042 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 009 Pixels @ 017,042 */ 9, 0x07,
  /* ABS: 004 Pixels @ 026,042 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 010 Pixels @ 030,042 */ 10, 0x00,
  /* ABS: 010 Pixels @ 040,042 */ 0, 10, 0x9F, 0xF3, 0x33, 0xFF, 0x1B,
  /* RLE: 028 Pixels @ 050,042 */ 28, 0x00,
  /* ABS: 004 Pixels @ 014,043 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 009 Pixels @ 018,043 */ 9, 0x07,
  /* ABS: 004 Pixels @ 027,043 */ 0, 4, 0x3F, 0xF9,
  /* RLE: 008 Pixels @ 031,043 */ 8, 0x00,
  /* ABS: 004 Pixels @ 039,043 */ 0, 4, 0xBF, 0xF3,
  /* RLE: 004 Pixels @ 043,043 */ 4, 0x07,
  /* ABS: 005 Pixels @ 047,043 */ 0, 5, 0x1F, 0xF5, 0xE0,
  /* RLE: 027 Pixels @ 052,043 */ 27, 0x00,
  /* ABS: 004 Pixels @ 015,044 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 009 Pixels @ 019,044 */ 9, 0x07,
  /* ABS: 004 Pixels @ 028,044 */ 0, 4, 0x3F, 0xF8,
  /* RLE: 006 Pixels @ 032,044 */ 6, 0x00,
  /* ABS: 004 Pixels @ 038,044 */ 0, 4, 0xBF, 0xF3,
  /* RLE: 006 Pixels @ 042,044 */ 6, 0x07,
  /* ABS: 005 Pixels @ 048,044 */ 0, 5, 0x3F, 0xF2, 0xD0,
  /* RLE: 027 Pixels @ 053,044 */ 27, 0x00,
  /* ABS: 004 Pixels @ 016,045 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 009 Pixels @ 020,045 */ 9, 0x07,
  /* ABS: 012 Pixels @ 029,045 */ 0, 12, 0x3F, 0xF5, 0xD0, 0x0D, 0x8F, 0xF3,
  /* RLE: 009 Pixels @ 041,045 */ 9, 0x07,
  /* RLE: 003 Pixels @ 050,045 */ 3, 0x0F,
  /* RLE: 001 Pixels @ 053,045 */ 1, 0x0B,
  /* RLE: 027 Pixels @ 054,045 */ 27, 0x00,
  /* ABS: 004 Pixels @ 017,046 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 009 Pixels @ 021,046 */ 9, 0x07,
  /* ABS: 010 Pixels @ 030,046 */ 0, 10, 0x3F, 0xFF, 0x11, 0xFF, 0xF3,
  /* RLE: 011 Pixels @ 040,046 */ 11, 0x07,
  /* ABS: 004 Pixels @ 051,046 */ 0, 4, 0x1F, 0xFB,
  /* RLE: 027 Pixels @ 055,046 */ 27, 0x00,
  /* ABS: 004 Pixels @ 018,047 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 009 Pixels @ 022,047 */ 9, 0x07,
  /* RLE: 001 Pixels @ 031,047 */ 1, 0x03,
  /* RLE: 005 Pixels @ 032,047 */ 5, 0x0F,
  /* ABS: 002 Pixels @ 037,047 */ 0, 2, 0x13,
  /* RLE: 013 Pixels @ 039,047 */ 13, 0x07,
  /* ABS: 004 Pixels @ 052,047 */ 0, 4, 0x3F, 0xFB,
  /* RLE: 027 Pixels @ 056,047 */ 27, 0x00,
  /* ABS: 004 Pixels @ 019,048 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 010 Pixels @ 023,048 */ 10, 0x07,
  /* ABS: 006 Pixels @ 033,048 */ 0, 6, 0x3F, 0xFF, 0x13,
  /* RLE: 014 Pixels @ 039,048 */ 14, 0x07,
  /* ABS: 004 Pixels @ 053,048 */ 0, 4, 0x3F, 0xFD,
  /* RLE: 027 Pixels @ 057,048 */ 27, 0x00,
  /* ABS: 004 Pixels @ 020,049 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 011 Pixels @ 024,049 */ 11, 0x07,
  /* RLE: 001 Pixels @ 035,049 */ 1, 0x01,
  /* RLE: 005 Pixels @ 036,049 */ 5, 0x0F,
  /* ABS: 002 Pixels @ 041,049 */ 0, 2, 0x33,
  /* RLE: 011 Pixels @ 043,049 */ 11, 0x07,
  /* ABS: 003 Pixels @ 054,049 */ 0, 3, 0x1F, 0x40,
  /* RLE: 028 Pixels @ 057,049 */ 28, 0x00,
  /* ABS: 004 Pixels @ 021,050 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 012 Pixels @ 025,050 */ 12, 0x07,
  /* RLE: 001 Pixels @ 037,050 */ 1, 0x03,
  /* RLE: 005 Pixels @ 038,050 */ 5, 0x0F,
  /* RLE: 001 Pixels @ 043,050 */ 1, 0x01,
  /* RLE: 011 Pixels @ 044,050 */ 11, 0x07,
  /* ABS: 003 Pixels @ 055,050 */ 0, 3, 0xFF, 0xC0,
  /* RLE: 028 Pixels @ 058,050 */ 28, 0x00,
  /* ABS: 004 Pixels @ 022,051 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 014 Pixels @ 026,051 */ 14, 0x07,
  /* ABS: 004 Pixels @ 040,051 */ 0, 4, 0x33, 0x13,
  /* RLE: 011 Pixels @ 044,051 */ 11, 0x07,
  /* ABS: 003 Pixels @ 055,051 */ 0, 3, 0x1F, 0xA0,
  /* RLE: 029 Pixels @ 058,051 */ 29, 0x00,
  /* ABS: 004 Pixels @ 023,052 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 028 Pixels @ 027,052 */ 28, 0x07,
  /* ABS: 003 Pixels @ 055,052 */ 0, 3, 0x1F, 0xA0,
  /* RLE: 030 Pixels @ 058,052 */ 30, 0x00,
  /* ABS: 004 Pixels @ 024,053 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 027 Pixels @ 028,053 */ 27, 0x07,
  /* ABS: 003 Pixels @ 055,053 */ 0, 3, 0xFF, 0xC0,
  /* RLE: 031 Pixels @ 058,053 */ 31, 0x00,
  /* ABS: 004 Pixels @ 025,054 */ 0, 4, 0x5F, 0xF3,
  /* RLE: 025 Pixels @ 029,054 */ 25, 0x07,
  /* ABS: 003 Pixels @ 054,054 */ 0, 3, 0x1F, 0x20,
  /* RLE: 033 Pixels @ 057,054 */ 33, 0x00,
  /* ABS: 004 Pixels @ 026,055 */ 0, 4, 0x6F, 0xF3,
  /* RLE: 023 Pixels @ 030,055 */ 23, 0x07,
  /* ABS: 004 Pixels @ 053,055 */ 0, 4, 0x1F, 0x1D,
  /* RLE: 034 Pixels @ 057,055 */ 34, 0x00,
  /* ABS: 004 Pixels @ 027,056 */ 0, 4, 0x8F, 0xF1,
  /* RLE: 021 Pixels @ 031,056 */ 21, 0x07,
  /* ABS: 004 Pixels @ 052,056 */ 0, 4, 0x1F, 0x1C,
  /* RLE: 036 Pixels @ 056,056 */ 36, 0x00,
  /* ABS: 004 Pixels @ 028,057 */ 0, 4, 0xAF, 0xFF,
  /* RLE: 019 Pixels @ 032,057 */ 19, 0x07,
  /* ABS: 004 Pixels @ 051,057 */ 0, 4, 0x1F, 0x1C,
  /* RLE: 038 Pixels @ 055,057 */ 38, 0x00,
  /* ABS: 005 Pixels @ 029,058 */ 0, 5, 0xC1, 0xFF, 0x30,
  /* RLE: 016 Pixels @ 034,058 */ 16, 0x07,
  /* ABS: 004 Pixels @ 050,058 */ 0, 4, 0xFF, 0x1C,
  /* RLE: 040 Pixels @ 054,058 */ 40, 0x00,
  /* ABS: 006 Pixels @ 030,059 */ 0, 6, 0xE6, 0xFF, 0xF3,
  /* RLE: 012 Pixels @ 036,059 */ 12, 0x07,
  /* ABS: 005 Pixels @ 048,059 */ 0, 5, 0x3F, 0xF1, 0xD0,
  /* RLE: 043 Pixels @ 053,059 */ 43, 0x00,
  /* ABS: 007 Pixels @ 032,060 */ 0, 7, 0xB2, 0xFF, 0xF3, 0x30,
  /* RLE: 007 Pixels @ 039,060 */ 7, 0x07,
  /* ABS: 006 Pixels @ 046,060 */ 0, 6, 0x3F, 0xFF, 0x5E,
  /* RLE: 046 Pixels @ 052,060 */ 46, 0x00,
  /* ABS: 002 Pixels @ 034,061 */ 0, 2, 0xB2,
  /* RLE: 005 Pixels @ 036,061 */ 5, 0x0F,
  /* RLE: 003 Pixels @ 041,061 */ 3, 0x01,
  /* RLE: 004 Pixels @ 044,061 */ 4, 0x0F,
  /* ABS: 002 Pixels @ 048,061 */ 0, 2, 0x1B,
  /* RLE: 050 Pixels @ 050,061 */ 50, 0x00,
  /* ABS: 003 Pixels @ 036,062 */ 0, 3, 0xC6, 0x10,
  /* RLE: 007 Pixels @ 039,062 */ 7, 0x0F,
  /* ABS: 002 Pixels @ 046,062 */ 0, 2, 0x5B,
  /* RLE: 055 Pixels @ 048,062 */ 55, 0x00,
  /* ABS: 007 Pixels @ 039,063 */ 0, 7, 0xDC, 0xBB, 0xBC, 0xE0,
  /* RLE: 018 Pixels @ 046,063 */ 18, 0x00,
  0
};  // 821 bytes for 4096 pixels

GUI_CONST_STORAGE GUI_BITMAP bmcalling0 = {
  64, // xSize
  64, // ySize
  32, // BytesPerLine
  GUI_COMPRESS_RLE4, // BitsPerPixel
  _accalling0,  // Pointer to picture data (indices)
  &_Palcalling0,  // Pointer to palette
  GUI_DRAW_RLE4
};

/*************************** End of file ****************************/
