/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "ViewNavigator.h"
#include "WM.h"
#include "DIALOG.h"
#include "Contact.h"
#include "ListView.h"






/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_02     (GUI_ID_USER + 0x10)
#define ID_LISTBOX_0     (GUI_ID_USER + 0x11)

void InitContactView(void);

static void Call(void);
static void CallCancelCallback(void);
static GUI_HWIN CallViewShow();
static uint32_t CallViewHide(GUI_HWIN hwin);


void EditProgress(void * arg, GUI_HWIN currentWidget);

extern ListApiHandlers_typedef ContactListApiHandlers;
extern View_Typedef ListView;

const char* FunctionDisplay[1] = { (const char*) "Call" };
const void (*Functions[1])(void) = {Call };

const CustomFunctionList_Typedef ContactFunctionList = { 1, FunctionDisplay,
		Functions };
const ListViewOption_typedef ContactListViewOption = { 1, 1, 1 };

typedef enum {
	EditContactState_Name,
	EditContactState_LastName,
	EditContactState_CallNumber,
	EditContactState_Finished,
} EditContactState_Typedef;

const View_Typedef CallView = {
		CONTACT_CALL_VIEW_ID, "Contact Call", "Call",
		(void *) NULL, CallViewShow, CallViewHide,
		NULL, (const char*) "Cancel", NULL, CallCancelCallback, NULL, 0 };


void InitContactView() {
	ListViewInit(&ContactListApiHandlers, ContactListViewOption,
			ContactFunctionList, sizeof(Contact_Typedef), EditProgress);
	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &ListView);
}



static void Call(void) {
	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &CallView);
}
static void CallCancelCallback(void) {
	ViewNavigator_GoHomeView(&DefaultViewNavigator);
}
static GUI_HWIN CallViewShow() {
	WM_HWIN hwin = WINDOW_CreateEx(0, 0, 128, 115, NULL, WM_CF_SHOW, 0x0,
	GUI_ID_USER, NULL);
	return hwin;
}
static uint32_t CallViewHide(GUI_HWIN hwin) {
	return 1;
}

void EditProgress(void * arg, GUI_HWIN currentWidget) {
	uint32_t len;
	Contact_Typedef *contact = arg;
	EditContactState_Typedef *state = arg + sizeof(Contact_Typedef);
	if (*state == EditContactState_Name) {
		TEXT_SetText(WM_GetDialogItem(currentWidget, GUI_ID_TEXT0), "Name");

		EDIT_SetText(WM_GetDialogItem(currentWidget, GUI_ID_EDIT0),
				(contact)->Name);


		*state = EditContactState_LastName;
	} else if (*state == EditContactState_LastName) {
		len = EDIT_GetNumChars(WM_GetDialogItem(currentWidget, GUI_ID_EDIT0));
		if (contact->Name != NULL)
			vPortFree(contact->Name);
		contact->Name = pvPortMalloc(len + 1);
		EDIT_GetText(WM_GetDialogItem(currentWidget, GUI_ID_EDIT0),
				(contact)->Name, len + 1);

		TEXT_SetText(WM_GetDialogItem(currentWidget, GUI_ID_TEXT0),
				"Last Name");

		EDIT_SetText(WM_GetDialogItem(currentWidget, GUI_ID_EDIT0),
				(contact)->LastName);


		*state = EditContactState_CallNumber;
	} else if (*state == EditContactState_CallNumber) {
		len = EDIT_GetNumChars(WM_GetDialogItem(currentWidget, GUI_ID_EDIT0));
		if (contact->LastName != NULL)
			vPortFree(contact->LastName);
		contact->LastName = pvPortMalloc(len + 1);
		EDIT_GetText(WM_GetDialogItem(currentWidget, GUI_ID_EDIT0),
				(contact)->LastName, len + 1);

		TEXT_SetText(WM_GetDialogItem(currentWidget, GUI_ID_TEXT0),
				"Call Number");

		EDIT_SetText(WM_GetDialogItem(currentWidget, GUI_ID_EDIT0),
				(contact)->CallNumber);



		*state = EditContactState_Finished;
	} else if (*state == EditContactState_Finished) {
		len = EDIT_GetNumChars(WM_GetDialogItem(currentWidget, GUI_ID_EDIT0));
		if (contact->CallNumber != NULL)
			vPortFree(contact->CallNumber);
		contact->CallNumber = pvPortMalloc(len + 1);
		EDIT_GetText(WM_GetDialogItem(currentWidget, GUI_ID_EDIT0),
				(contact)->CallNumber, len + 1);

		memcpy(&ContactList->current_item, contact, sizeof(Contact_Typedef));
		ViewNavigator_GoBackView(&DefaultViewNavigator);
		ViewNavigator_GoBackView(&DefaultViewNavigator);
		*state = EditContactState_Name;
	}
}




// USER END

/*************************** End of file ****************************/
