/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "WM.h"
#include "MenuContainerDLG.h"
#include "SessionInformation.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_LISTBOX_0     (GUI_ID_USER + 0x01)


// USER START (Optionally insert additional defines)
static void 	select_Click_Callback	(void);
static void		startup (void);
static void		show (void *, int);
WM_HWIN CreateContactOption(void);
const PageItem_Typedef ContactOptionPageItem=
{
	ContactOptionPageID,
	"Contact Option",
	"Option",
	(void *) NULL,
	CreateContactOption,
	startup,
	NULL,
	show,
	NULL,
	select_Click_Callback,
	NULL,
};

DMRServicesContact_Type  * SelectedContact;

extern PageItem_Typedef CtrlServicesPageItem;
extern PageItem_Typedef ViewContactPageItem;
extern PageItem_Typedef EditContactPageItem;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "ContactOption", ID_WINDOW_0, 0, 0, 160, 84, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "ContactOptionListBox", ID_LISTBOX_0, 1, 1, 158, 82, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'ContactOptionListBox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "Ctrl Services");
    LISTBOX_AddString(hItem, "View Contact");
    LISTBOX_AddString(hItem, "Edit Contact");
    LISTBOX_AddString(hItem, "Del Contact");
    // USER START (Optionally insert additional code for further widget initialization)
	    SetListBoxSkin(hItem);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTBOX_0: // Notifications sent by 'ContactOptionListBox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateContactOption
*/

WM_HWIN CreateContactOption(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

static void		startup (void)
{
	PageManager_RegisterPage(pageManager,& CtrlServicesPageItem);
	PageManager_RegisterPage(pageManager,& ViewContactPageItem);
	PageManager_RegisterPage(pageManager,& EditContactPageItem);

}

static void		show	(void *param,int isForward)
{
	if (param != NULL)
		SelectedContact = (DMRServicesContact_Type *) param;

}
static void 	select_Click_Callback()
{
	int idx = LISTBOX_GetSel(WM_GetDialogItem(CURRENT_PAGE.hWindow, ID_LISTBOX_0));
	switch (idx) {
	case 0:
		PageManager_GoToPageOfByID(pageManager, CtrlServicesPageID, SelectedContact);
		break;
	case 1:
		PageManager_GoToPageOfByID(pageManager, ViewContactPageID, SelectedContact);
		break;
	case 2:
		PageManager_GoToPageOfByID(pageManager, EditContactPageID, SelectedContact);
		break;
	case 3:
		SessionInformation_cpy(SelectedContact->CallAlias, "/0", 1);
		PageManager_GoBackPage(pageManager);
		break;

	default:
		break;
	}
}
// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
