/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "ViewNavigator.h"
#include "WM.h"
#include "DIALOG.h"
#include "Contact.h"
#include "ListView.h"






/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_02     (GUI_ID_USER + 0x10)
#define ID_LISTBOX_0     (GUI_ID_USER + 0x11)

void InitContactView(void);

static void Call(void);
static void CallCancelCallback(void);
static GUI_HWIN CallViewShow();
static uint32_t CallViewHide(GUI_HWIN hwin);

CustomFunction_Typedef * ContactFunctionList[5];
static void EditContactProgress(void * arg, GUI_HWIN currentWidget);

extern ListApiHandlers_typedef ContactListApiHandlers;
extern View_Typedef ListView;

static const CustomFunction_Typedef CallFunction = {
NULL, (const char*) "Call", Call };


typedef enum {
	EditContactState_Name,
	EditContactState_LastName,
	EditContactState_CallNumber,
	EditContactState_Finished,
} EditContactState_Typedef;

const View_Typedef CallView = {
		CONTACT_CALL_VIEW_ID, "Contact Call", "Call",
		(void *) NULL, CallViewShow, CallViewHide,
		NULL, (const char*) "Cancel", NULL, CallCancelCallback, NULL, 0 };


void InitContactView() {
	ContactFunctionList[0] = &CallFunction;
	ContactFunctionList[1] = &EditFunction;
	ContactFunctionList[2] = &ViewInfoFunction;
	ContactFunctionList[3] = &DeleteFunction;
	ContactFunctionList[4] = NULL;
	ListViewInit(&ContactListApiHandlers,
			ContactFunctionList, sizeof(Contact_Typedef), EditContactProgress);
	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &ListView);
}



static void Call(void) {
	ViewNavigator_GoToViewOf(&DefaultViewNavigator, &CallView);
}
static void CallCancelCallback(void) {
	ViewNavigator_GoHomeView(&DefaultViewNavigator);
}
static GUI_HWIN CallViewShow() {
	WM_HWIN hwin = WINDOW_CreateEx(0, 0, 128, 115, NULL, WM_CF_SHOW, 0x0,
	GUI_ID_USER, NULL);
	return hwin;
}
static uint32_t CallViewHide(GUI_HWIN hwin) {
	return 1;
}

static void EditContactProgress(void * arg, GUI_HWIN currentWidget) {
	uint32_t len;
	Contact_Typedef *contact = arg;
	EditContactState_Typedef *state = arg + sizeof(Contact_Typedef);
	if (*state == EditContactState_Name) {
		GUI_HWIN textHwin = TEXT_CreateAsChild(5, 20, 118, 40, currentWidget,
				GUI_ID_TEXT0, WM_CF_SHOW, "", TEXT_CF_TOP | TEXT_CF_HCENTER);
		GUI_HWIN editHwin = EDIT_CreateAsChild(5, 65, 118, 40, currentWidget,
				GUI_ID_EDIT0, WM_CF_SHOW, 15);
		WM_SetFocus(editHwin);
		EDIT_SetTextMode(editHwin);

		TEXT_SetText(textHwin, "Name");
		EDIT_SetText(editHwin, (contact)->Name);


		*state = EditContactState_LastName;
	} else if (*state == EditContactState_LastName) {
		GUI_HWIN editHwin = WM_GetDialogItem(currentWidget, GUI_ID_EDIT0);
		GUI_HWIN textHwin = WM_GetDialogItem(currentWidget, GUI_ID_TEXT0);
		len = EDIT_GetNumChars(editHwin);
		if (contact->Name != NULL)
			vPortFree(contact->Name);
		contact->Name = pvPortMalloc(len + 1);
		EDIT_GetText(editHwin, (contact)->Name, len + 1);

		TEXT_SetText(textHwin, "Last Name");
		EDIT_SetText(editHwin, (contact)->LastName);

		*state = EditContactState_CallNumber;
	} else if (*state == EditContactState_CallNumber) {
		GUI_HWIN editHwin = WM_GetDialogItem(currentWidget, GUI_ID_EDIT0);
		GUI_HWIN textHwin = WM_GetDialogItem(currentWidget, GUI_ID_TEXT0);
		len = EDIT_GetNumChars(editHwin);
		if (contact->LastName != NULL)
			vPortFree(contact->LastName);
		contact->LastName = pvPortMalloc(len + 1);
		EDIT_GetText(editHwin, (contact)->LastName, len + 1);

		TEXT_SetText(textHwin, "Call Number");
		EDIT_SetText(editHwin, (contact)->CallNumber);

		*state = EditContactState_Finished;
	} else if (*state == EditContactState_Finished) {
		GUI_HWIN editHwin = WM_GetDialogItem(currentWidget, GUI_ID_EDIT0);
		len = EDIT_GetNumChars(editHwin);
		if (contact->CallNumber != NULL)
			vPortFree(contact->CallNumber);
		contact->CallNumber = pvPortMalloc(len + 1);
		EDIT_GetText(editHwin, (contact)->CallNumber, len + 1);

		memcpy(&ContactList->current_item, contact, sizeof(Contact_Typedef));
		ViewNavigator_GoBackView(&DefaultViewNavigator);
		ViewNavigator_GoBackView(&DefaultViewNavigator);
		*state = EditContactState_Name;
	}
}




// USER END

/*************************** End of file ****************************/
