/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "WM.h"
#include "MenuContainerDLG.h"
#include "SessionInformation.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_LISTBOX_0     (GUI_ID_USER + 0x01)


// USER START (Optionally insert additional defines)
static void 	select_Click_Callback	(void);
static void		startup (void);
static void		show	(void *, int);
static uint8_t	hide	(void);
static void		fill_contact_list();

WM_HWIN 		CreateContactList(void);
const PageItem_Typedef ContactListPageItem=
{
	ContactListPageID,
	"Contact List",
	"List",
	(void *) NULL,
	CreateContactList,
	startup,
	NULL,
	show,
	hide,
	select_Click_Callback,
	NULL,
};

int 					count;
uint32_t 				**Data;
DMRServicesContact_Type *SelectedData;

extern PageItem_Typedef ContactOptionPageItem;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "ContactList", ID_WINDOW_0, 0, 0, 160, 84, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "ContactList", ID_LISTBOX_0, 1, 1, 158, 82, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'ContactListWheel'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);

    // USER START (Optionally insert additional code for further widget initialization)
    SetListBoxSkin(hItem);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTBOX_0: // Notifications sent by 'ContactListWheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateContactList
*/
WM_HWIN CreateContactList(void);
WM_HWIN CreateContactList(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
static void		startup (void)
{
	PageManager_RegisterPage(pageManager,& ContactOptionPageItem);

}
static void		show	(void *param, int isForward)
{
	if (isForward)
		SelectedData = NULL;
	if (param!=NULL)
		SelectedData = (DMRServicesContact_Type *) param;
	int *datatemp[30];
	count = 0;
	for (int i=0; i<30; i++)
		if (session->DMRService.DMRServicesContacts[i].CallAlias[0] != 0)
			datatemp[count++] = & session->DMRService.DMRServicesContacts[i];
	Data=malloc((count) * sizeof(uint32_t));
	memcpy(Data,datatemp,count * 4);
	fill_contact_list();
}
static uint8_t	hide	(void)
{
	WM_HWIN hWin = WM_GetDialogItem(CURRENT_PAGE.hWindow, ID_LISTBOX_0);
	int j = LISTBOX_GetNumItems(hWin);
	for (int i =0; i<j;i++)
		LISTBOX_DeleteItem(hWin, 0);
	count = 0;
	free(Data);
	return 1;
}
static void 	select_Click_Callback()
{
	SelectedData = (DMRServicesContact_Type *) Data[LISTBOX_GetSel(WM_GetDialogItem(CURRENT_PAGE.hWindow, ID_LISTBOX_0))];
	int inMessageMenu = ExistPageIDInRouteVerify(pageManager,MessagePageID);
	if (inMessageMenu==0)
		PageManager_GoToPageOfByID(pageManager, ContactOptionPageID, SelectedData);
}

static void		fill_contact_list()
{
	WM_HWIN hWin = WM_GetDialogItem(CURRENT_PAGE.hWindow, ID_LISTBOX_0);
	for (int i = 0; i < count; i++)
		LISTBOX_AddString(hWin, ((DMRServicesContact_Type *)Data[i])->CallAlias);
	for (int i=0; i< count; i++)
		if(Data[i]==SelectedData)
			LISTBOX_SetSel(WM_GetDialogItem(CURRENT_PAGE.hWindow, ID_LISTBOX_0), i);

}
// USER END

/*************************** End of file ****************************/
